## Series

In [3]:
import numpy as np
import pandas as pd

In [2]:
srs = pd.Series([4,7,-5,2])

srs

0    4
1    7
2   -5
3    2
dtype: int64

In [3]:
type(srs)

pandas.core.series.Series

In [7]:
arr = srs.array
arr

<NumpyExtensionArray>
[4, 7, -5, 2]
Length: 4, dtype: int64

In [8]:
srs.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
print(obj2['b'])

7

In [13]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

sr = pd.Series(sdata)

In [15]:
sr.head()

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
sr.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [17]:
states = ["California", "Ohio", "Oregon", "Texas"]

ssr = pd.Series(sdata , index=states)

In [20]:
ssr

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isna(ssr)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.isnull(ssr)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
s= ssr + sr

In [25]:
s.name = 'population'
s.index.name = 'state'

In [26]:
s

state
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
Name: population, dtype: float64

In [28]:
srs

0    4
1    7
2   -5
3    2
dtype: int64

In [29]:
srs.index = ['Anand','virat','rohit','dhoni']

In [30]:
srs

Anand    4
virat    7
rohit   -5
dhoni    2
dtype: int64

## DataFrame

In [31]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }

In [35]:
print(data)
print(type(data))

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
<class 'dict'>

In [85]:
df = pd.DataFrame(data)

In [86]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [61]:
df1 = pd.DataFrame(data , columns=["year", "state", "pop", "debt"])

df1

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [62]:
df1.fillna('hi')

   year   state  pop debt
0  2000    Ohio  1.5   hi
1  2001    Ohio  1.7   hi
2  2002    Ohio  3.6   hi
3  2001  Nevada  2.4   hi
4  2002  Nevada  2.9   hi
5  2003  Nevada  3.2   hi

In [82]:
df1.loc[1] = np.nan
df1

     year   state  pop debt
0  2000.0    Ohio  1.5  NaN
1     NaN     NaN  NaN  NaN
2  2002.0    Ohio  3.6  NaN
3  2001.0  Nevada  2.4  NaN
4  2002.0  Nevada  2.9  NaN
5  2003.0  Nevada  3.2  NaN

In [64]:
# df1.fillna('hello')

     year   state    pop   debt
0  2000.0    Ohio    1.5  hello
1   hello   hello  hello  hello
2  2002.0    Ohio    3.6  hello
3  2001.0  Nevada    2.4  hello
4  2002.0  Nevada    2.9  hello
5  2003.0  Nevada    3.2  hello

In [83]:
df1['state'] = df1['state'].fillna('not available')

df1

     year          state  pop debt
0  2000.0           Ohio  1.5  NaN
1     NaN  not available  NaN  NaN
2  2002.0           Ohio  3.6  NaN
3  2001.0         Nevada  2.4  NaN
4  2002.0         Nevada  2.9  NaN
5  2003.0         Nevada  3.2  NaN

In [87]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [91]:
df.iloc[1:3,1:3]

   year  pop
1  2001  1.7
2  2002  3.6

# Filtering Out Missing Data

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [5]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [8]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data.dropna()  # drop row if any value is NaN
data.dropna(how='all')  # drop row if all are NaN

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = np.nan

In [13]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis='columns' , how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data.dropna(thresh = 2) # drop row with NaN value > 2

     0    1    2   4
0  1.0  6.5  3.0 NaN
3  NaN  6.5  3.0 NaN

# Filling In Missing Data

In [24]:
df = pd.DataFrame(np.arange(20).reshape((5,4)))

In [25]:
df

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [73]:
df.iloc[0:2,3:3] = np.nan
df.iloc[3:5,0:2] = np.nan

In [74]:
df

     0    1   2     3
0  0.0  1.0   2   NaN
1  4.0  5.0   6   NaN
2  8.0  9.0  10  11.0
3  NaN  NaN  14  15.0
4  NaN  NaN  18  19.0

In [37]:
# df.fillna(100)

       0      1   2      3
0    0.0    1.0   2  100.0
1    4.0    5.0   6  100.0
2    8.0    9.0  10   11.0
3  100.0  100.0  14   15.0
4  100.0  100.0  18   19.0

In [41]:
df.fillna({1:100,0:0,2:200,3:300}) # fill NaN value by specifying columns

     0      1   2      3
0  0.0    1.0   2  300.0
1  4.0    5.0   6  300.0
2  8.0    9.0  10   11.0
3  0.0  100.0  14   15.0
4  0.0  100.0  18   19.0

In [42]:
df.iloc[0:2,3:3] = np.nan
df.iloc[3:5,0:2] = np.nan

In [43]:
df

     0    1   2     3
0  0.0  1.0   2   NaN
1  4.0  5.0   6   NaN
2  8.0  9.0  10  11.0
3  NaN  NaN  14  15.0
4  NaN  NaN  18  19.0

In [50]:
df.bfill(inplace=True)    # fill column wise after value
df.ffill(inplace=True)    # fill column wise previous value 
df

     0    1   2     3
0  0.0  1.0   2  11.0
1  4.0  5.0   6  11.0
2  8.0  9.0  10  11.0
3  8.0  9.0  14  15.0
4  8.0  9.0  18  19.0

In [54]:
data = pd.Series([3,np.nan, 9,np.nan , 6])

In [55]:
data

0    3.0
1    NaN
2    9.0
3    NaN
4    6.0
dtype: float64

In [57]:
data.fillna(data.mean()) # fill NaN with mean

0    3.0
1    6.0
2    9.0
3    6.0
4    6.0
dtype: float64

In [62]:
df.iloc[0:2,3:4] = np.nan
df.iloc[3:5,0:2] = np.nan

In [63]:
df

     0    1   2     3
0  0.0  1.0   2   NaN
1  4.0  5.0   6   NaN
2  8.0  9.0  10  11.0
3  NaN  NaN  14  15.0
4  NaN  NaN  18  19.0

In [78]:
df.fillna(df.mean(axis = 0))    # in dataframe replace NaN with columnwise mean
df.fillna(df.mean(axis = 1))    # in dataframe replace NaN with rowwise mean mean take column number of that cell and replace it with mean if that number

     0    1   2     3
0  0.0  1.0   2  14.5
1  4.0  5.0   6  14.5
2  8.0  9.0  10  11.0
3  1.0  5.0  14  15.0
4  1.0  5.0  18  19.0

# Data Transformation

## Removing Duplicates

In [79]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})

In [80]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [81]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [82]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [84]:
data['k3'] = np.arange(7)

In [85]:
data

    k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [86]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [87]:
data.drop_duplicates(subset=['k1'])

    k1  k2  k3
0  one   1   0
1  two   1   1

In [90]:
data.drop_duplicates(subset=['k1','k2'] ,keep='last')   # drop the row with duplicates of k1,k2 and keep last matched row

    k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data Using a Function or Mapping

In [91]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [92]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [93]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}

In [94]:
data['animal'] = data['food'].map(meat_to_animal)

In [95]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [96]:
def get_animal(x):
    return meat_to_animal[x]

data['animal'] = data['food'].map(get_animal)

In [97]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

## Replacing Values

In [108]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [109]:
data.replace([-999,-1000] , [np.nan , 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## Renaming Axis Indexes

In [133]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=["Ohio", "Colorado", "New York"],columns=["one", "two", "three", "four"])

In [134]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [137]:
def transform(x):
    return x[:].upper()

data.index =  data.index.map(transform)

In [138]:
data

          one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [139]:
 data.rename(index=str.title, columns=str.upper)

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

## Discretization and Binning

In [140]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [143]:
bins = [18, 25, 35, 60, 100]

In [144]:
age_cat = pd.cut(ages , bins)      # include right bracket
# age_cat = pd.cut(ages , bins , right=False)      # include left bracket

In [148]:
print(type(age_cat))
age_cat

<class 'pandas.core.arrays.categorical.Categorical'>

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [150]:
age_cat.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [151]:
age_cat.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [153]:
pd.Series(age_cat).value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [154]:
 group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [155]:
pd.cut(ages , bins , labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [156]:
data = np.random.uniform(size=20)

In [157]:
data

array([0.90659987, 0.10828422, 0.73797347, 0.93535803, 0.64254108,
       0.68302806, 0.39417906, 0.07238785, 0.68185093, 0.41937413,
       0.50872435, 0.9281468 , 0.22359627, 0.14646029, 0.82069032,
       0.0048412 , 0.4033543 , 0.36836111, 0.44645816, 0.27556691])

In [158]:
 pd.cut(data, 4, precision=2)

[(0.7, 0.94], (0.0039, 0.24], (0.7, 0.94], (0.7, 0.94], (0.47, 0.7], ..., (0.0039, 0.24], (0.24, 0.47], (0.24, 0.47], (0.24, 0.47], (0.24, 0.47]]
Length: 20
Categories (4, interval[float64, right]): [(0.0039, 0.24] < (0.24, 0.47] < (0.47, 0.7] < (0.7, 0.94]]

## Detecting and Filtering Outliers

In [58]:
df = pd.DataFrame(np.random.standard_normal((100,4)))

In [59]:
df

           0         1         2         3
0   0.119537 -0.415629  0.127379  0.026613
1   0.809415 -1.214501  0.258357 -0.678013
2  -0.512752  0.531954  0.834858 -0.066927
3  -1.421210 -1.432681 -0.456965 -0.236606
4   0.604468 -1.327865  1.834680 -0.473064
..       ...       ...       ...       ...
95 -0.407866 -1.222166 -1.066358 -1.551854
96  1.903402  0.973687 -1.041331  0.696744
97  0.668132  0.161151  0.409102  0.607004
98 -1.036483  0.736039  0.153655  0.518618
99  2.528137 -0.236523 -1.370048  1.058313

[100 rows x 4 columns]

In [60]:
df.describe()

                0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean     0.089183   -0.056791   -0.042022   -0.198530
std      1.091536    1.015686    1.004804    1.011514
min     -2.739145   -2.323723   -2.477878   -2.928606
25%     -0.619989   -0.751913   -0.760736   -0.858156
50%      0.120328    0.015529    0.023224   -0.197329
75%      0.809884    0.573779    0.651859    0.488486
max      2.528137    3.168562    2.544467    1.938150

In [65]:
col = df[1]

In [66]:
type(col)

pandas.core.series.Series

In [67]:
col[col.abs() > 3]

86    3.168562
Name: 1, dtype: float64

In [62]:
type(df)

pandas.core.frame.DataFrame

In [36]:
df.iloc[:,:]

           0         1         2         3
0  -1.026475 -2.213761 -0.677778 -0.507677
1   0.474921  0.262390  0.009978 -0.256093
2  -1.547607 -0.524902  1.107086 -1.095806
3  -0.058072  0.347151 -1.563458 -1.282443
4   0.521131  0.750484  0.712043  0.225357
..       ...       ...       ...       ...
95  0.337135  0.514056 -0.795661  0.495505
96  0.463055  1.555376  0.426745 -0.252988
97  1.109300 -1.396853 -1.715549 -2.020242
98 -2.248886  0.019666  0.229414 -0.312127
99 -1.014721  0.859012 -0.786749  1.451652

[100 rows x 4 columns]

In [63]:
 df[(df.abs() > 3).any(axis="columns")]

           0         1         2         3
86  1.597727  3.168562 -0.405095  0.075654

In [73]:
df[df.abs() > 3] = np.sign(df)*3         # np.sign() give 1 if x>0 0 if x=0 -1 if x<0

In [69]:
df

           0         1         2         3
0   0.119537 -0.415629  0.127379  0.026613
1   0.809415 -1.214501  0.258357 -0.678013
2  -0.512752  0.531954  0.834858 -0.066927
3  -1.421210 -1.432681 -0.456965 -0.236606
4   0.604468 -1.327865  1.834680 -0.473064
..       ...       ...       ...       ...
95 -0.407866 -1.222166 -1.066358 -1.551854
96  1.903402  0.973687 -1.041331  0.696744
97  0.668132  0.161151  0.409102  0.607004
98 -1.036483  0.736039  0.153655  0.518618
99  2.528137 -0.236523 -1.370048  1.058313

[100 rows x 4 columns]

In [71]:
df.describe()

                0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean     0.089183   -0.058476   -0.042022   -0.198530
std      1.091536    1.010406    1.004804    1.011514
min     -2.739145   -2.323723   -2.477878   -2.928606
25%     -0.619989   -0.751913   -0.760736   -0.858156
50%      0.120328    0.015529    0.023224   -0.197329
75%      0.809884    0.573779    0.651859    0.488486
max      2.528137    3.000000    2.544467    1.938150

In [72]:
df.iloc[86]

0    1.597727
1    3.000000
2   -0.405095
3    0.075654
Name: 86, dtype: float64

In [74]:
np.sign(df).head()

     0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0 -1.0  1.0 -1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4  1.0 -1.0  1.0 -1.0

## Permutation and Random Sampling

In [75]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [76]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [80]:
sample = np.random.permutation(5)

In [81]:
sample

array([3, 2, 4, 0, 1], dtype=int32)

In [82]:
df.take(sample)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [83]:
col_samp = np.random.permutation(7)

In [84]:
col_samp

array([2, 4, 3, 6, 0, 5, 1], dtype=int32)

In [89]:
df.take(col_samp , axis = 1)

    2   4   3   6   0   5   1
0   2   4   3   6   0   5   1
1   9  11  10  13   7  12   8
2  16  18  17  20  14  19  15
3  23  25  24  27  21  26  22
4  30  32  31  34  28  33  29

In [92]:
df.sample(3)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [93]:
choices = pd.Series([5, 7, -1, 6, 4])

In [98]:
choices.sample(n=10 , replace=True)    # draw 10 numbers from the series given left is index in series and right is number from series

1    7
0    5
4    4
0    5
2   -1
1    7
4    4
3    6
2   -1
1    7
dtype: int64

# Computing Indicator/Dummy Variables

In [99]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],"data1": range(6)})

In [100]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [103]:
dff = pd.get_dummies(df['key'])  # meas in which row a comes then a column is true else false

In [105]:
df1 = df[['key']].join(dff)

df1

  key      a      b      c
0   b  False   True  False
1   b  False   True  False
2   a   True  False  False
3   c  False  False   True
4   a   True  False  False
5   b  False   True  False

In [106]:
import pandas as pd

data = {
    "movie_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "title": [
        "Toy Story (1995)", "Jumanji (1995)", "Grumpier Old Men (1995)",
        "Waiting to Exhale (1995)", "Father of the Bride Part II (1995)",
        "Heat (1995)", "Sabrina (1995)", "Tom and Huck (1995)",
        "Sudden Death (1995)", "GoldenEye (1995)"
    ],
    "genres": [
        "Animation|Children's|Comedy", "Adventure|Children's|Fantasy",
        "Comedy|Romance", "Comedy|Drama", "Comedy",
        "Action|Crime|Thriller", "Comedy|Romance",
        "Adventure|Children's", "Action", "Action|Adventure|Thriller"
    ]
}

movies = pd.DataFrame(data)

In [107]:
movies

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [108]:
dummies = movies['genres'].str.get_dummies('|')

In [109]:
dummies

,Action,Adventure,Animation,Children's,Comedy,Crime,Drama,Fantasy,Romance,Thriller
0,0,0,1,1,1,0,0,0,0,0
1,0,1,0,1,0,0,0,1,0,0
2,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,1,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,0
5,1,0,0,0,0,1,0,0,0,1
6,0,0,0,0,1,0,0,0,1,0
7,0,1,0,1,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0
9,1,1,0,0,0,0,0,0,0,1

In [110]:
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [111]:
all_mvs = movies.join(dummies.add_prefix('Genre_'))

In [112]:
all_mvs

,movie_id,title,genres,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Crime,Genre_Drama,Genre_Fantasy,Genre_Romance,Genre_Thriller
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,1,1,1,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,1,0,1,0,0,0,1,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,1,0,0,0,1,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,1,0,1,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,1,0,0,0,0,0
5,6,Heat (1995),Action|Crime|Thriller,1,0,0,0,0,1,0,0,0,1
6,7,Sabrina (1995),Comedy|Romance,0,0,0,0,1,0,0,0,1,0
7,8,Tom and Huck (1995),Adventure|Children's,0,1,0,1,0,0,0,0,0,0
8,9,Sudden Death (1995),Action,1,0,0,0,0,0,0,0,0,0
9,10,GoldenEye (1995),Action|Adventure|Thriller,1,1,0,0,0,0,0,0,0,1

In [113]:
all_mvs.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
Genre_Action                                  0
Genre_Adventure                               0
Genre_Animation                               1
Genre_Children's                              1
Genre_Comedy                                  1
Genre_Crime                                   0
Genre_Drama                                   0
Genre_Fantasy                                 0
Genre_Romance                                 0
Genre_Thriller                                0
Name: 0, dtype: object

In [117]:
np.random.seed(12345)

# String Manipulation

🔹 2. Basics of Regex (VERY IMPORTANT)

Before pandas, understand this:

Pattern	Meaning
\d	digits (0–9)
\w	letters + digits
\s	whitespace
.	any character
^	start of string
$	end of string
+	one or more
*	zero or more
?	optional

In [119]:
string = "I want to maintain consistency , discipilne , patience, and hard work"

string.split(",")

['I want to maintain consistency ',
 ' discipilne ',
 ' patience',
 ' and hard work']

In [120]:
block = [x.strip() for x in string.split(',')]

In [121]:
block

['I want to maintain consistency', 'discipilne', 'patience', 'and hard work']

In [124]:
fst,scd,thd,frth = block

fst + "::" + scd + "::" + thd + "::" + frth

'I want to maintain consistency::discipilne::patience::and hard work'

In [126]:
"::".join(block)

'I want to maintain consistency::discipilne::patience::and hard work'

In [127]:
string.index(',')

31

In [129]:
string.find(":")

-1

In [130]:
string.replace(',' , ';')

'I want to maintain consistency ; discipilne ; patience; and hard work'

In [136]:
import re
text = "foo    bar\t baz  \tqux"

re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [137]:
regex = re.compile('\s+')

In [139]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

## String function in Pandas

In [140]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com","Rob": "rob@gmail.com", "Wes": np.nan}

In [141]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [142]:
data = pd.Series(data)

In [143]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [144]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [145]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [146]:
data_str = data.astype("string")

In [147]:
data_str

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [148]:
data_str.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [150]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [151]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [153]:
data.str.extract(pattern, flags=re.IGNORECASE)            # convert into dataframe

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## Categorical Data

In [154]:
 values = pd.Series(['apple', 'orange', 'apple','apple'] * 2)

In [155]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [156]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [158]:
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [159]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])

In [160]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [161]:
dim

0     apple
1    orange
dtype: object

In [162]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object