## Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
srs = pd.Series([4,7,-5,2])

srs

0    4
1    7
2   -5
3    2
dtype: int64

In [3]:
type(srs)

pandas.core.series.Series

In [7]:
arr = srs.array
arr

<NumpyExtensionArray>
[4, 7, -5, 2]
Length: 4, dtype: int64

In [8]:
srs.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
print(obj2['b'])

7

In [13]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

sr = pd.Series(sdata)

In [15]:
sr.head()

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
sr.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [17]:
states = ["California", "Ohio", "Oregon", "Texas"]

ssr = pd.Series(sdata , index=states)

In [20]:
ssr

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isna(ssr)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.isnull(ssr)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
s= ssr + sr

In [25]:
s.name = 'population'
s.index.name = 'state'

In [26]:
s

state
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
Name: population, dtype: float64

In [28]:
srs

0    4
1    7
2   -5
3    2
dtype: int64

In [29]:
srs.index = ['Anand','virat','rohit','dhoni']

In [30]:
srs

Anand    4
virat    7
rohit   -5
dhoni    2
dtype: int64

## DataFrame

In [31]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }

In [35]:
print(data)
print(type(data))

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
<class 'dict'>

In [85]:
df = pd.DataFrame(data)

In [86]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [61]:
df1 = pd.DataFrame(data , columns=["year", "state", "pop", "debt"])

df1

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [62]:
df1.fillna('hi')

   year   state  pop debt
0  2000    Ohio  1.5   hi
1  2001    Ohio  1.7   hi
2  2002    Ohio  3.6   hi
3  2001  Nevada  2.4   hi
4  2002  Nevada  2.9   hi
5  2003  Nevada  3.2   hi

In [82]:
df1.loc[1] = np.nan
df1

     year   state  pop debt
0  2000.0    Ohio  1.5  NaN
1     NaN     NaN  NaN  NaN
2  2002.0    Ohio  3.6  NaN
3  2001.0  Nevada  2.4  NaN
4  2002.0  Nevada  2.9  NaN
5  2003.0  Nevada  3.2  NaN

In [64]:
# df1.fillna('hello')

     year   state    pop   debt
0  2000.0    Ohio    1.5  hello
1   hello   hello  hello  hello
2  2002.0    Ohio    3.6  hello
3  2001.0  Nevada    2.4  hello
4  2002.0  Nevada    2.9  hello
5  2003.0  Nevada    3.2  hello

In [83]:
df1['state'] = df1['state'].fillna('not available')

df1

     year          state  pop debt
0  2000.0           Ohio  1.5  NaN
1     NaN  not available  NaN  NaN
2  2002.0           Ohio  3.6  NaN
3  2001.0         Nevada  2.4  NaN
4  2002.0         Nevada  2.9  NaN
5  2003.0         Nevada  3.2  NaN

In [87]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [91]:
df.iloc[1:3,1:3]

   year  pop
1  2001  1.7
2  2002  3.6