In [4]:
from io import StringIO
import pandas as pd

In [9]:
import os

print("Current:", os.getcwd())
print("Parent:", os.listdir(".."))
print("Data folder:", os.listdir("../datasets"))
df = pd.read_csv('../datasets/mercedesbenz.csv')

Current: C:\Users\Anand Patidar\Desktop\Python_ML\Pandas
Parent: ['.git', '.ipynb_checkpoints', 'datasets', 'IPL_IMPACT_ANALYSIS', 'IPL_Impact_of_Player_Analysis.ipynb', 'MatPlotLib', 'NumPy', 'OOPs', 'Pandas', 'pydata-book', 'Python_Basics(L,S,D,T,Fun)']
Data folder: ['.ipynb_checkpoints', 'mercedesbenz.csv']

In [ ]:
df.head()

In [5]:
data = ('Col1,Col2,Col3\n'
        'x,y,z\n'
       'a,b,c\n'
       '1,2,3')

In [6]:
type(data)

str

In [7]:
StringIO(data)

In [25]:
df1 = pd.read_csv(StringIO(data))

In [9]:
pd.read_csv(StringIO(data) , usecols=['Col1','Col2'])

  Col1 Col2
0    x    y
1    a    b
2    1    2

In [10]:
df = pd.read_csv('../datasets/mercedesbenz.csv' , usecols=['X3','X4','X5','X6','X8'] , dtype='object')

In [22]:
df.head(10)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X3      4209 non-null   object
 1   X4      4209 non-null   object
 2   X5      4209 non-null   object
 3   X6      4209 non-null   object
 4   X8      4209 non-null   object
dtypes: object(5)
memory usage: 164.5+ KB

In [11]:
df.to_csv('../datasets/Test.csv',index=False)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X3      4209 non-null   object
 1   X4      4209 non-null   object
 2   X5      4209 non-null   object
 3   X6      4209 non-null   object
 4   X8      4209 non-null   object
dtypes: object(5)
memory usage: 164.5+ KB

In [24]:
df.isnull().sum()

X3    0
X4    0
X5    0
X6    0
X8    0
dtype: int64

In [26]:
df1.head()

  Col1 Col2 Col3
0    x    y    z
1    a    b    c
2    1    2    3

In [28]:
df1['Col1'][1]

'a'

In [40]:
##datatypes in csv
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [47]:
df = pd.read_csv(StringIO(data) , dtype={'a':int,'b':float,'c' : object,'d':str} , index_col=0)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       3 non-null      float64
 1   c       3 non-null      object
 2   d       2 non-null      object
dtypes: float64(1), object(2)
memory usage: 96.0+ bytes

In [49]:
df.head()

      b   c    d
a
1   2.0   3    4
5   6.0   7    8
9  10.0  11  NaN

In [55]:
df = pd.read_csv(StringIO(data),usecols=['b','c'] , index_col=0)

In [56]:
df.head()

     c
b
2    3
6    7
10  11