- Pandas is a powerful Python library used for data manipulation, data analysis, and data cleaning. It provides two main data structures: Series (1D) and DataFrame (2D).

Intuition (Simple Explanation)

Think of Pandas like Excel inside Python:

Rows → records (students, products)
Columns → features (name, marks, price)

# Playing with Dataframe

In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame(np.arange(20).reshape((5,4)) , index = ['Row1','Row2','Row3','Row4','Row5'] , columns = ['Column1','Column2','Column3',"Column4"])


    # pd.Dataframe( Data , Index/Rows , Columns)

In [3]:
print(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [5]:
df.to_csv('test1.csv')

In [8]:
df.loc['Row2']

Column1    4
Column2    5
Column3    6
Column4    7
Name: Row2, dtype: int64

In [9]:
print(df.loc['Row1'])

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [19]:
type(df.loc['Row3'])     # Accessing the Row using loc

pandas.core.series.Series

In [20]:
print(df.loc[:,'Column2'])   # Accessing Column using loc

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int64

In [21]:
type(df.loc[:,'Column2'])

pandas.core.series.Series

In [23]:
print(df.loc[['Row1','Row2']])
type(df.loc[['Row1','Row2']])

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

pandas.core.frame.DataFrame

In [24]:
print(df.loc[:,['Column2','Column3']])

      Column2  Column3
Row1        1        2
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

In [25]:
type(df.loc[:,['Column2','Column3']])

pandas.core.frame.DataFrame

In [27]:
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [30]:
df.iloc[:,:]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [31]:
df.iloc[0:2,0:2]

      Column1  Column2
Row1        0        1
Row2        4        5

In [32]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [33]:
df.iloc[0:2,0:1]

      Column1
Row1        0
Row2        4

In [39]:
type(df.iloc[0:2,0:1])       # Will be a DataFrame

pandas.core.frame.DataFrame

In [40]:
df.iloc[0:3,1]                # Will be a Series

Row1    1
Row2    5
Row3    9
Name: Column2, dtype: int64

In [37]:
type(df.iloc[0:3,1])

pandas.core.series.Series

In [42]:
df.iloc[0:3,0:2].values           # Converting a DataFrame into an Array

array([[0, 1],
       [4, 5],
       [8, 9]])

In [47]:
df.isnull().sum()                # Cheking a null value in column

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [56]:
df.iloc[1:2,2:3] = 10
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5       10        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [58]:
df['Column3'].value_counts()    # Count the frequency in a column

Column3
10    2
2     1
14    1
18    1
Name: count, dtype: int64

In [61]:
df.iloc[1:2,2:3] = 6
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [73]:
df['Column2']

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Column2, dtype: int64

In [74]:
df

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [81]:
df.head(3)     # First 3 rows

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11

In [82]:
df.tail(2)      # Last 2 rows

      Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [80]:
df.describe()

         Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

## Pandas DataFrame Manipulation

In [1]:
import pandas as pd

data = {
    'Name': ['Aman', 'Riya', 'Raj', 'Simran', 'Karan'],
    'Age': [20, 21, 19, 22, 20],
    'Marks': [85, 90, 78, 92, 88],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai']
}

df = pd.DataFrame(data)

In [2]:
print(df)

     Name  Age  Marks    City
0    Aman   20     85   Delhi
1    Riya   21     90  Mumbai
2     Raj   19     78   Delhi
3  Simran   22     92    Pune
4   Karan   20     88  Mumbai

In [5]:
df.head()

     Name  Age  Marks    City
0    Aman   20     85   Delhi
1    Riya   21     90  Mumbai
2     Raj   19     78   Delhi
3  Simran   22     92    Pune
4   Karan   20     88  Mumbai

In [7]:
rws = df.iloc[0:3,:]
print(rws)

   Name  Age  Marks    City
0  Aman   20     85   Delhi
1  Riya   21     90  Mumbai
2   Raj   19     78   Delhi

In [8]:
df.head(3)

   Name  Age  Marks    City
0  Aman   20     85   Delhi
1  Riya   21     90  Mumbai
2   Raj   19     78   Delhi

In [9]:
df[['Name','Marks']]

     Name  Marks
0    Aman     85
1    Riya     90
2     Raj     78
3  Simran     92
4   Karan     88

In [11]:
df[df['Marks'] > 85]

     Name  Age  Marks    City
1    Riya   21     90  Mumbai
3  Simran   22     92    Pune
4   Karan   20     88  Mumbai

In [15]:
df['Passed'] = np.where(df['Marks'] >= 80 , 'Pass' , 'Fail')

In [16]:
df.head()

     Name  Age  Marks    City Passed
0    Aman   20     85   Delhi   Pass
1    Riya   21     90  Mumbai   Pass
2     Raj   19     78   Delhi   Fail
3  Simran   22     92    Pune   Pass
4   Karan   20     88  Mumbai   Pass

In [18]:
avgg = np.mean(df['Marks'])
print(avgg)

86.6

## Another Dataset

In [3]:
data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Price': [70000, 20000, 30000, 75000, 22000],
    'Quantity': [3, 5, 2, 4, 6],
    'City': ['Delhi', 'Delhi', 'Mumbai', 'Mumbai', 'Delhi']
}

df = pd.DataFrame(data)

In [4]:
df.head()

  Product  Price  Quantity    City
0  Laptop  70000         3   Delhi
1   Phone  20000         5   Delhi
2  Tablet  30000         2  Mumbai
3  Laptop  75000         4  Mumbai
4   Phone  22000         6   Delhi

In [5]:
df['Total Sales'] = df['Price'] * df['Quantity']

df.head()

  Product  Price  Quantity    City  Total Sales
0  Laptop  70000         3   Delhi       210000
1   Phone  20000         5   Delhi       100000
2  Tablet  30000         2  Mumbai        60000
3  Laptop  75000         4  Mumbai       300000
4   Phone  22000         6   Delhi       132000

In [16]:
total_sales = df.groupby('Product')['Total Sales'].sum()
print(total_sales)

Product
Laptop    510000
Phone     232000
Tablet     60000
Name: Total Sales, dtype: int64

In [15]:
df.head()

  Product  Price  Quantity    City  Total Sales
0  Laptop  70000         3   Delhi       210000
1   Phone  20000         5   Delhi       100000
2  Tablet  30000         2  Mumbai        60000
3  Laptop  75000         4  Mumbai       300000
4   Phone  22000         6   Delhi       132000

In [22]:
prods = df[df['City'] == 'Delhi']

prods.head()

  Product  Price  Quantity   City  Total Sales
0  Laptop  70000         3  Delhi       210000
1   Phone  20000         5  Delhi       100000
4   Phone  22000         6  Delhi       132000

In [27]:
srt = df.sort_values('Price',ascending = False)
print(srt)

  Product  Price  Quantity    City  Total Sales
3  Laptop  75000         4  Mumbai       300000
0  Laptop  70000         3   Delhi       210000
2  Tablet  30000         2  Mumbai        60000
4   Phone  22000         6   Delhi       132000
1   Phone  20000         5   Delhi       100000

In [29]:
hgt_sale = df.max()
print(hgt_sale)

Product        Tablet
Price           75000
Quantity            6
City           Mumbai
Total Sales    300000
dtype: object

In [34]:
print(df.loc[df['Total Sales'].idxmax()])

Product        Laptop
Price           75000
Quantity            4
City           Mumbai
Total Sales    300000
Name: 3, dtype: object

## Another Dataset

In [45]:
data = {
    'Name': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Department': ['IT', 'HR', 'IT', 'HR', 'IT', 'HR'],
    'Salary': [60000, 50000, 70000, 52000, 65000, 58000],
    'Experience': [2, 3, 5, 1, 4, 2]
}

df = pd.DataFrame(data)

In [50]:
df.head(6)

  Name Department  Salary  Experience
0    A         IT   60000           2
1    B         HR   50000           3
2    C         IT   70000           5
3    D         HR   52000           1
4    E         IT   65000           4
5    F         HR   58000           2

- Find average salary per department

In [38]:
avg_sal = df.groupby('Department')['Salary'].mean()

print(avg_sal)

Department
HR    53333.333333
IT    65000.000000
Name: Salary, dtype: float64

- Find employee with highest salary in each department

In [55]:
idx = df.groupby('Department')['Salary'].idxmax()
emp = df.loc[idx]
print(emp)

  Name Department  Salary  Experience
5    F         HR   58000           2
2    C         IT   70000           5

- Add a column "Senior"

- Condition:

- Experience >= 3 → Yes
- Else → No

In [58]:
df['Senior'] = np.where(df['Experience'] >= 3 , "Yes", "No")

df.head()

  Name Department  Salary  Experience Senior
0    A         IT   60000           2     No
1    B         HR   50000           3    Yes
2    C         IT   70000           5    Yes
3    D         HR   52000           1     No
4    E         IT   65000           4    Yes

- Filter employees:
- Salary > 55000 AND Department = IT

In [70]:
emp = df[((df['Salary'] > 57000) & (df['Department'] == 'IT'))]
print(emp)

  Name Department  Salary  Experience Senior
0    A         IT   60000           2     No
2    C         IT   70000           5    Yes
4    E         IT   65000           4    Yes

- Rank employees based on Salary

In [72]:
df.head(6)

  Name Department  Salary  Experience Senior
0    A         IT   60000           2     No
1    B         HR   50000           3    Yes
2    C         IT   70000           5    Yes
3    D         HR   52000           1     No
4    E         IT   65000           4    Yes
5    F         HR   58000           2     No

In [85]:
df['Rank'] = df['Salary'].rank(ascending = False)

In [86]:
df.head()

  Name Department  Salary  Experience Senior  Rank
0    A         IT   60000           2     No   3.0
1    B         HR   50000           3    Yes   6.0
2    C         IT   70000           5    Yes   1.0
3    D         HR   52000           1     No   5.0
4    E         IT   65000           4    Yes   2.0

## Another Dataset

In [102]:
data = {
    'OrderID': [101,102,103,104,105,106],
    'Customer': ['Aman','Riya','Aman','Raj','Riya','Simran'],
    'Amount': [500,700,300,400,900,1000],
    'Status': ['Completed','Pending','Completed','Completed','Pending','Completed']
}

df = pd.DataFrame(data)

In [89]:
df.head(7)

   OrderID Customer  Amount     Status
0      101     Aman     500  Completed
1      102     Riya     700    Pending
2      103     Aman     300  Completed
3      104      Raj     400  Completed
4      105     Riya     900    Pending
5      106   Simran    1000  Completed

- Total amount spent by each customer

In [134]:
amt = df.groupby('Customer')['Amount'].sum()
print(amt)

Customer
Aman       800
Raj        400
Riya      1600
Simran    1000
Name: Amount, dtype: int64

- Count number of completed orders

In [104]:
print((df['Status'] == 'Completed').sum())

4

- Find customers who spent more than 800 total

In [110]:
amt.head()

Customer
Aman       800
Raj        400
Riya      1600
Simran    1000
Name: Amount, dtype: int64

In [120]:
mt = df.groupby('Customer')['Amount'].sum()
mt[mt>800]

Customer
Riya      1600
Simran    1000
Name: Amount, dtype: int64

- Find average order amount

In [124]:
avgg = df['Amount'].mean()
print(avgg)

633.3333333333334

- Sort customers by total spending

In [136]:
srt = amt.sort_values(ascending = False)

In [137]:
print(srt)

Customer
Riya      1600
Simran    1000
Aman       800
Raj        400
Name: Amount, dtype: int64