# Dataset 1

In [1]:
import pandas as pd

data = {
    "order_id": [101,102,103,104,105,106,107,108,109,110],
    "customer": ["A","B","A","C","B","D","E","A","C","D"],
    "category": ["Electronics","Clothing","Electronics","Clothing","Clothing","Electronics","Electronics","Clothing","Clothing","Electronics"],
    "amount": [1200,800,1500,400,700,2000,1800,500,650,2200],
    "payment_mode": ["UPI","COD","Card","UPI","Card","UPI","COD","Card","UPI","Card"],
    "rating": [5,4,None,3,5,4,5,None,4,5]
}

df = pd.DataFrame(data)

In [6]:
import numpy as np

In [5]:
df.head(10)

   order_id customer     category  amount payment_mode  rating
0       101        A  Electronics    1200          UPI     5.0
1       102        B     Clothing     800          COD     4.0
2       103        A  Electronics    1500         Card     NaN
3       104        C     Clothing     400          UPI     3.0
4       105        B     Clothing     700         Card     5.0
5       106        D  Electronics    2000          UPI     4.0
6       107        E  Electronics    1800          COD     5.0
7       108        A     Clothing     500         Card     NaN
8       109        C     Clothing     650          UPI     4.0
9       110        D  Electronics    2200         Card     5.0

- Tasks
- Find all orders where amount > 1000 and payment_mode = 'UPI'
- Calculate total spending per customer
- Find the average rating per category (ignore missing values)
- Create a new column discounted_amount where:
- 10% discount if amount > 1500, else no discount
- Identify the top 2 customers based on total spending
- Sort categories by their total revenue (descending)

In [26]:
cond = ((df['amount'] > 1000) & (df['payment_mode'] == 'UPI'))
df1 = df[cond]

In [29]:
type(df1)

print(df1)

df1.head(10)

   order_id customer     category  amount payment_mode  rating
0       101        A  Electronics    1200          UPI     5.0
5       106        D  Electronics    2000          UPI     4.0

   order_id customer     category  amount payment_mode  rating
0       101        A  Electronics    1200          UPI     5.0
5       106        D  Electronics    2000          UPI     4.0

In [40]:
ttl_spend = df.groupby('customer',as_index=False)['amount'].sum()


type(ttl_spend)    # Series if as_index = True but DataFrame if as_index = False
ttl_spend.head()

# df2 = pd.DataFrame(ttl_spend)             convert series into dataframe
# df2.head()

  customer  amount
0        A    3200
1        B    1500
2        C    1050
3        D    4200
4        E    1800

In [45]:
avg_rating = df.groupby('category' , as_index=False)['rating'].mean()
type(avg_rating)

avg_rating.head()

      category  rating
0     Clothing    4.00
1  Electronics    4.75

In [50]:
cond = df['amount'] > 1500
discamt = df['amount'] * 0.90

df['discounted_amount'] = np.where(cond , discamt , df['amount'])

In [51]:
df.head(10)

,order_id,customer,category,amount,payment_mode,rating,discounted_amount
0,101,A,Electronics,1200,UPI,5.0,1200.0
1,102,B,Clothing,800,COD,4.0,800.0
2,103,A,Electronics,1500,Card,NaN,1500.0
3,104,C,Clothing,400,UPI,3.0,400.0
4,105,B,Clothing,700,Card,5.0,700.0
5,106,D,Electronics,2000,UPI,4.0,1800.0
6,107,E,Electronics,1800,COD,5.0,1620.0
7,108,A,Clothing,500,Card,NaN,500.0
8,109,C,Clothing,650,UPI,4.0,650.0
9,110,D,Electronics,2200,Card,5.0,1980.0

In [55]:
df2 = df.groupby('customer',as_index=False)['amount'].sum()
df2.head(10)

sorted_df = df2.sort_values('amount' , ascending=False)
sorted_df.head(2)

  customer  amount
3        D    4200
0        A    3200

In [58]:
df3 = df.groupby('category' , as_index=False)['amount'].sum()
df3.head(10)

df3.sort_values('amount',ascending=False)

      category  amount
1  Electronics    8700
0     Clothing    3050

# Dataset 2

In [59]:
data = {
    "student_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["A","B","C","D","E","F","G","H","I","J"],
    "math": [80,70,90,None,60,85,75,95,88,None],
    "science": [78,65,92,70,60,80,None,98,85,75],
    "english": [85,60,88,75,70,None,80,90,87,78],
    "attendance": [90,85,95,80,70,88,92,96,89,75]
}

df = pd.DataFrame(data)

In [60]:
df.head(10)

   student_id name  math  science  english  attendance
0           1    A  80.0     78.0     85.0          90
1           2    B  70.0     65.0     60.0          85
2           3    C  90.0     92.0     88.0          95
3           4    D   NaN     70.0     75.0          80
4           5    E  60.0     60.0     70.0          70
5           6    F  85.0     80.0      NaN          88
6           7    G  75.0      NaN     80.0          92
7           8    H  95.0     98.0     90.0          96
8           9    I  88.0     85.0     87.0          89
9          10    J   NaN     75.0     78.0          75

- Tasks
- Fill missing marks with subject-wise mean
- Create a column average_score
- Filter students with average_score > 80 and attendance > 85
- Rank students based on average_score
- Find subject-wise highest scorer
- Sort students by attendance and then by average_score

In [76]:
# mathmean = df['math'].mean()
# sciencemean = df['science'].mean()
# englishmean = df['english'].mean()

mn = df[['math','science','english']].mean()

df[['math','science','english']] = df[['math','science','english']].fillna(mn)

# df1 = np.where(df[['math','science','english']].isna() , mn ,df[['math','science','english']])

type(df)

df.head(10)

   student_id name    math    science    english  attendance
0           1    A  80.000  78.000000  85.000000          90
1           2    B  70.000  65.000000  60.000000          85
2           3    C  90.000  92.000000  88.000000          95
3           4    D  80.375  70.000000  75.000000          80
4           5    E  60.000  60.000000  70.000000          70
5           6    F  85.000  80.000000  79.222222          88
6           7    G  75.000  78.111111  80.000000          92
7           8    H  95.000  98.000000  90.000000          96
8           9    I  88.000  85.000000  87.000000          89
9          10    J  80.375  75.000000  78.000000          75

In [78]:
df['average_score'] = df[['math','science','english']].mean(axis = 1)
df.head(10)

   student_id name    math    science    english  attendance  average_score
0           1    A  80.000  78.000000  85.000000          90      81.000000
1           2    B  70.000  65.000000  60.000000          85      65.000000
2           3    C  90.000  92.000000  88.000000          95      90.000000
3           4    D  80.375  70.000000  75.000000          80      75.125000
4           5    E  60.000  60.000000  70.000000          70      63.333333
5           6    F  85.000  80.000000  79.222222          88      81.407407
6           7    G  75.000  78.111111  80.000000          92      77.703704
7           8    H  95.000  98.000000  90.000000          96      94.333333
8           9    I  88.000  85.000000  87.000000          89      86.666667
9          10    J  80.375  75.000000  78.000000          75      77.791667

In [81]:
cond = ((df['average_score'] > 80) & (df['attendance'] > 85))

df[cond].head(10)

   student_id name  math  science    english  attendance  average_score
0           1    A  80.0     78.0  85.000000          90      81.000000
2           3    C  90.0     92.0  88.000000          95      90.000000
5           6    F  85.0     80.0  79.222222          88      81.407407
7           8    H  95.0     98.0  90.000000          96      94.333333
8           9    I  88.0     85.0  87.000000          89      86.666667

In [87]:
df['Rank'] = df['average_score'].rank(ascending=False)

df.head(10)

,student_id,name,math,science,english,attendance,average_score,Rank
0,1,A,80.000,78.000000,85.000000,90,81.000000,5.0
1,2,B,70.000,65.000000,60.000000,85,65.000000,9.0
2,3,C,90.000,92.000000,88.000000,95,90.000000,2.0
3,4,D,80.375,70.000000,75.000000,80,75.125000,8.0
4,5,E,60.000,60.000000,70.000000,70,63.333333,10.0
5,6,F,85.000,80.000000,79.222222,88,81.407407,4.0
6,7,G,75.000,78.111111,80.000000,92,77.703704,7.0
7,8,H,95.000,98.000000,90.000000,96,94.333333,1.0
8,9,I,88.000,85.000000,87.000000,89,86.666667,3.0
9,10,J,80.375,75.000000,78.000000,75,77.791667,6.0

In [112]:
idx1 = df['math'].argmax()
idx2 = df['science'].argmax()
idx3 = df['english'].argmax()

# df.loc[[idx1,idx2,idx3]]

topper = {

     'math' : df.loc[idx1 , ['name', 'math']],
    'science' : df.loc[idx2 ,['name', 'science']],
    'english' : df.loc[idx3 , ['name', 'english']]
}

print(topper)

{'math': name       H
math    95.0
Name: 7, dtype: object, 'science': name          H
science    98.0
Name: 7, dtype: object, 'english': name          H
english    90.0
Name: 7, dtype: object}

In [114]:
df.sort_values(['attendance','average_score'] ,ascending=[False,False] )

,student_id,name,math,science,english,attendance,average_score,Rank
7,8,H,95.000,98.000000,90.000000,96,94.333333,1.0
2,3,C,90.000,92.000000,88.000000,95,90.000000,2.0
6,7,G,75.000,78.111111,80.000000,92,77.703704,7.0
0,1,A,80.000,78.000000,85.000000,90,81.000000,5.0
8,9,I,88.000,85.000000,87.000000,89,86.666667,3.0
5,6,F,85.000,80.000000,79.222222,88,81.407407,4.0
1,2,B,70.000,65.000000,60.000000,85,65.000000,9.0
3,4,D,80.375,70.000000,75.000000,80,75.125000,8.0
9,10,J,80.375,75.000000,78.000000,75,77.791667,6.0
4,5,E,60.000,60.000000,70.000000,70,63.333333,10.0

# Dataset 3

In [136]:
data = {
    "emp_id": [1,2,3,4,5,6,7,8,9,10],
    "department": ["IT","HR","IT","Finance","HR","IT","Finance","HR","IT","Finance"],
    "salary": [60000,40000,75000,50000,42000,80000,52000,45000,70000,55000],
    "experience": [2,3,5,4,2,6,5,3,4,6],
    "performance_score": [4,3,5,4,2,5,4,3,4,5]
}

df = pd.DataFrame(data)

In [137]:
df.head(10)

   emp_id department  salary  experience  performance_score
0       1         IT   60000           2                  4
1       2         HR   40000           3                  3
2       3         IT   75000           5                  5
3       4    Finance   50000           4                  4
4       5         HR   42000           2                  2
5       6         IT   80000           6                  5
6       7    Finance   52000           5                  4
7       8         HR   45000           3                  3
8       9         IT   70000           4                  4
9      10    Finance   55000           6                  5

- Tasks
- Find average salary per department
- Filter employees with salary above department average
- Create a column salary_band:
- Low (<50k), Medium (50k–70k), High (>70k)
- Count employees in each salary_band per department
- Find top performer in each department
- Sort employees by performance_score and experience

In [148]:
davg = df.groupby('department')['salary'].mean()
# davg.head()

df['dept_avg'] = df['department'].map(davg)
cond = df['salary'] > df['dept_avg']

df[cond]

   emp_id department  salary  experience  performance_score      dept_avg
2       3         IT   75000           5                  5  71250.000000
5       6         IT   80000           6                  5  71250.000000
7       8         HR   45000           3                  3  42333.333333
9      10    Finance   55000           6                  5  52333.333333

In [154]:
cond1 = df['salary'] < 50000
cond2 = ((df['salary'] >= 50000) &  (df['salary'] < 70000))
cond3 = df['salary'] >= 70000

cond 

df['salary_band'] = np.select([cond1,cond2,cond3] , ['Low',"Medium",'High'] ,default='unknown')
df.head(10)

,emp_id,department,salary,experience,performance_score,dept_avg,salary_band
0,1,IT,60000,2,4,71250.000000,Medium
1,2,HR,40000,3,3,42333.333333,Low
2,3,IT,75000,5,5,71250.000000,High
3,4,Finance,50000,4,4,52333.333333,Medium
4,5,HR,42000,2,2,42333.333333,Low
5,6,IT,80000,6,5,71250.000000,High
6,7,Finance,52000,5,4,52333.333333,Medium
7,8,HR,45000,3,3,42333.333333,Low
8,9,IT,70000,4,4,71250.000000,High
9,10,Finance,55000,6,5,52333.333333,Medium

In [157]:
df.groupby(['department','salary_band'])['emp_id'].count()

department  salary_band
Finance     Medium         3
HR          Low            3
IT          High           3
            Medium         1
Name: emp_id, dtype: int64

In [161]:
idx = df.groupby('department')['performance_score'].idxmax()
df.loc[idx]

,emp_id,department,salary,experience,performance_score,dept_avg,salary_band
9,10,Finance,55000,6,5,52333.333333,Medium
1,2,HR,40000,3,3,42333.333333,Low
2,3,IT,75000,5,5,71250.000000,High

In [162]:
df.sort_values(['performance_score','experience'] , ascending=[False,False])

,emp_id,department,salary,experience,performance_score,dept_avg,salary_band
5,6,IT,80000,6,5,71250.000000,High
9,10,Finance,55000,6,5,52333.333333,Medium
2,3,IT,75000,5,5,71250.000000,High
6,7,Finance,52000,5,4,52333.333333,Medium
3,4,Finance,50000,4,4,52333.333333,Medium
8,9,IT,70000,4,4,71250.000000,High
0,1,IT,60000,2,4,71250.000000,Medium
1,2,HR,40000,3,3,42333.333333,Low
7,8,HR,45000,3,3,42333.333333,Low
4,5,HR,42000,2,2,42333.333333,Low

# Dataset 4

In [163]:
orders = pd.DataFrame({
    "order_id": [1,2,3,4,5,6,7,8,9,10],
    "customer_id": [101,102,101,103,104,102,105,101,103,104],
    "product_id": [201,202,203,201,204,202,203,204,201,203],
    "quantity": [1,2,1,3,2,1,2,1,2,3]
})

products = pd.DataFrame({
    "product_id": [201,202,203,204],
    "category": ["Electronics","Clothing","Electronics","Accessories"],
    "price": [1000,500,1500,700]
})

customers = pd.DataFrame({
    "customer_id": [101,102,103,104,105],
    "city": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai"]
})

- Tasks
- Merge all datasets into a single DataFrame
- Create a column total_price = quantity * price
- Find total revenue per city
- Find the most popular category (by quantity sold)
- Identify the top 2 customers based on total spending
- Find which city has the highest average order value

In [165]:
orders.head(10)

   order_id  customer_id  product_id  quantity
0         1          101         201         1
1         2          102         202         2
2         3          101         203         1
3         4          103         201         3
4         5          104         204         2
5         6          102         202         1
6         7          105         203         2
7         8          101         204         1
8         9          103         201         2
9        10          104         203         3

In [166]:
products.head()

   product_id     category  price
0         201  Electronics   1000
1         202     Clothing    500
2         203  Electronics   1500
3         204  Accessories    700

In [167]:
customers.head()

   customer_id       city
0          101      Delhi
1          102     Mumbai
2          103      Delhi
3          104  Bangalore
4          105     Mumbai

In [179]:
dff = orders.merge(products , left_on='product_id',right_on='product_id')

df = dff.merge(customers , left_on='customer_id' , right_on='customer_id')

df.head(10)

   order_id  customer_id  product_id  quantity     category  price       city
0         1          101         201         1  Electronics   1000      Delhi
1         2          102         202         2     Clothing    500     Mumbai
2         3          101         203         1  Electronics   1500      Delhi
3         4          103         201         3  Electronics   1000      Delhi
4         5          104         204         2  Accessories    700  Bangalore
5         6          102         202         1     Clothing    500     Mumbai
6         7          105         203         2  Electronics   1500     Mumbai
7         8          101         204         1  Accessories    700      Delhi
8         9          103         201         2  Electronics   1000      Delhi
9        10          104         203         3  Electronics   1500  Bangalore

In [180]:
df['total_price'] = df['price']*df['quantity']

In [181]:
df.head(10)

,order_id,customer_id,product_id,quantity,category,price,city,total_price
0,1,101,201,1,Electronics,1000,Delhi,1000
1,2,102,202,2,Clothing,500,Mumbai,1000
2,3,101,203,1,Electronics,1500,Delhi,1500
3,4,103,201,3,Electronics,1000,Delhi,3000
4,5,104,204,2,Accessories,700,Bangalore,1400
5,6,102,202,1,Clothing,500,Mumbai,500
6,7,105,203,2,Electronics,1500,Mumbai,3000
7,8,101,204,1,Accessories,700,Delhi,700
8,9,103,201,2,Electronics,1000,Delhi,2000
9,10,104,203,3,Electronics,1500,Bangalore,4500

In [183]:
df.groupby('city' , as_index=False)['total_price'].sum()

        city  total_price
0  Bangalore         5900
1      Delhi         8200
2     Mumbai         4500

In [187]:
 df.groupby('category', as_index=False)['quantity'].sum().sort_values('quantity',ascending=False).head(1)

      category  quantity
2  Electronics        12

In [197]:
df.groupby('customer_id',as_index=False)['total_price'].sum().sort_values('total_price',ascending=False).head(2)

   customer_id  total_price
3          104         5900
2          103         5000

In [206]:
df.groupby('city',as_index=False)['total_price'].mean().sort_values('total_price',ascending=False).head(1)

        city  total_price
0  Bangalore       2950.0

In [204]:
dataf = df.groupby('order_id',as_index=False)['total_price'].sum()

df.merge(dataf , on='order_id')

# dataf.groupby('city',as_index=False)['total_price'].mean().sort_values('total_price',ascending=False).head(1)

,order_id,customer_id,product_id,quantity,category,price,city,total_price_x,total_price_y
0,1,101,201,1,Electronics,1000,Delhi,1000,1000
1,2,102,202,2,Clothing,500,Mumbai,1000,1000
2,3,101,203,1,Electronics,1500,Delhi,1500,1500
3,4,103,201,3,Electronics,1000,Delhi,3000,3000
4,5,104,204,2,Accessories,700,Bangalore,1400,1400
5,6,102,202,1,Clothing,500,Mumbai,500,500
6,7,105,203,2,Electronics,1500,Mumbai,3000,3000
7,8,101,204,1,Accessories,700,Delhi,700,700
8,9,103,201,2,Electronics,1000,Delhi,2000,2000
9,10,104,203,3,Electronics,1500,Bangalore,4500,4500

In [205]:
# Step 1: Order-level total
dataf = df.groupby('order_id', as_index=False)['total_price'].sum()

# Step 2: Get unique order → city mapping
order_city = df[['order_id', 'city']].drop_duplicates()

# Step 3: Merge to bring city
dataf = dataf.merge(order_city, on='order_id')

# Step 4: Average order value per city
result = dataf.groupby('city', as_index=False)['total_price'].mean()

# Step 5: Get highest
result = result.sort_values('total_price', ascending=False).head(1)

print(result)

        city  total_price
0  Bangalore       2950.0

# Dataset 5

In [207]:
data = {
    "order_id": [1,2,3,4,5,6,7,8,9,10],
    "region": ["North","South","East","West","North","South","East","West","North","South"],
    "sales": [200, None, 300, 400, None, 500, 600, None, 700, 800],
    "profit": [20, 30, None, 50, 60, None, 80, 90, None, 100],
    "discount": [5,10,15,5,10,15,5,10,15,5]
}

df = pd.DataFrame(data)

In [208]:
df.head(10)

   order_id region  sales  profit  discount
0         1  North  200.0    20.0         5
1         2  South    NaN    30.0        10
2         3   East  300.0     NaN        15
3         4   West  400.0    50.0         5
4         5  North    NaN    60.0        10
5         6  South  500.0     NaN        15
6         7   East  600.0    80.0         5
7         8   West    NaN    90.0        10
8         9  North  700.0     NaN        15
9        10  South  800.0   100.0         5

- Tasks
- Fill missing sales with region-wise mean
- Fill missing profit with overall median
- Create a new column profit_margin = profit / sales
- Identify regions where average profit_margin > 0.1
- Rank regions based on total sales
- Sort dataset based on profit_margin descending

In [224]:
dff = df.groupby('region',as_index=False)['sales'].transform('mean')

df['sales'] = df['sales'].fillna(dff)
df.head(10)

   order_id region  sales  profit  discount
0         1  North  200.0    20.0         5
1         2  South  650.0    30.0        10
2         3   East  300.0     NaN        15
3         4   West  400.0    50.0         5
4         5  North  450.0    60.0        10
5         6  South  500.0     NaN        15
6         7   East  600.0    80.0         5
7         8   West  400.0    90.0        10
8         9  North  700.0     NaN        15
9        10  South  800.0   100.0         5