# Pandas with JSON

- In Part we are going to learn about

- read Json (read_json)
- To Json(to_json)
- Json Normalize

In [5]:
data =' {"employee_name": "James", "email": "james@gmail.com", "job_profile": {"title1":"Team Lead", "title2":"Sr. Developer"}}'

data1 = [{"employee_name": "James", "email": "james@gmail.com", "job_profile": {"title1":"Team Lead", "title2":"Sr. Developer"}}]

In [2]:
import pandas as pd
from io import StringIO

In [28]:
type(data)
type(data1)

dict

In [22]:
import pandas as pd
from io import StringIO

print(type(pd.read_json(StringIO(data))))   # dataframe

<class 'pandas.core.frame.DataFrame'>

In [33]:
pd.read_json(StringIO(data) , orient='records')

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [34]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [37]:
df

      col 1 col 2
row 1     a     b
row 2     c     d

In [35]:
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [36]:
df.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [38]:
df.to_json(orient='columns')

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [39]:
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [40]:
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [41]:
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [42]:
schema = '{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [44]:
pd.read_json(StringIO(schema) , orient='table')

      col 1 col 2
row 1     a     b
row 2     c     d

In [6]:
pd.json_normalize(data1)

  employee_name            email job_profile.title1 job_profile.title2
0         James  james@gmail.com          Team Lead      Sr. Developer

In [10]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {"age" : 21 , "Gender" : "Male"},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [11]:
type(data)

pd.json_normalize(data)

    id        name  fitness.height  fitness.weight   age Gender
0  1.0   Cole Volk           130.0            60.0   NaN    NaN
1  NaN    Mark Reg           130.0            60.0   NaN    NaN
2  NaN         NaN             NaN             NaN  21.0   Male
3  2.0  Faye Raker           130.0            60.0   NaN    NaN

In [15]:
pd.json_normalize(data , max_level=1)

    id        name  fitness.height  fitness.weight   age Gender
0  1.0   Cole Volk           130.0            60.0   NaN    NaN
1  NaN    Mark Reg           130.0            60.0   NaN    NaN
2  NaN         NaN             NaN             NaN  21.0   Male
3  2.0  Faye Raker           130.0            60.0   NaN    NaN

In [16]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [17]:
pd.json_normalize(data)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [20]:
pd.json_normalize(data,max_level=1)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [27]:
pd.json_normalize(data, 'counties' , ['state' , 'shortname' , ['info','governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

In [3]:
df = pd.read_csv('IPL.csv',low_memory = False)

In [4]:
df.tail(20)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278185,277936,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,16,5,...,143,101,6,Azmatullah Omarzai,1,1,0,"('Azmatullah Omarzai', 'Shashank Singh')",NaN,False
278186,277937,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,16,6,...,144,102,6,NaN,23,15,0,"('Azmatullah Omarzai', 'Shashank Singh')",NaN,False
278187,277938,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,1,...,145,103,6,NaN,23,16,0,"('Azmatullah Omarzai', 'Shashank Singh')",NaN,False
278188,277939,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,2,...,145,104,7,NaN,1,2,1,"('Azmatullah Omarzai', 'Shashank Singh')",KA Jamieson,True
278189,277940,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,3,...,146,105,7,KA Jamieson,0,1,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278190,277941,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,4,...,148,106,7,NaN,25,17,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278191,277942,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,5,...,149,107,7,NaN,26,18,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278192,277943,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,17,6,...,149,108,7,NaN,0,2,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278193,277944,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,1,...,155,109,7,NaN,32,19,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278194,277945,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,2,...,155,110,7,NaN,32,20,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278195,277946,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,3,...,155,111,7,NaN,32,21,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278196,277947,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,4,...,159,112,7,NaN,36,22,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278197,277948,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,5,...,161,113,7,NaN,38,23,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278198,277949,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,18,6,...,162,114,7,NaN,39,24,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278199,277950,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,1,...,162,115,7,NaN,39,25,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,...,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,...,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,...,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,...,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,...,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

# Pandas with HTML

- In this Part we are going to learn about

- read HTML(read_html)
- To HTML(to_html)

In [31]:
import pandas as pd
from io import StringIO

In [38]:
html = pd.read_html("https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India" , storage_options={'User-Agent': 'Mozilla/5.0'})

type(html)

list

In [40]:
print(html)

[    States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1                                                vte,                 State Administrative/ Executive capital  \
0      Andhra Pradesh                         Amaravati
1   Arunachal Pradesh                          Itanagar
2               Assam                            Dispur
3               Bihar                             Patna
4        Chhattisgarh                         Raipur[c]
5                 Goa                         Panaji[d]
6             Gujarat                       Gandhinagar
7             Haryana                        Chandigarh
8    Himachal Pradesh                            Shimla
9           Jharkhand                            Ranchi
10          Karnataka                         Bengaluru
11             Kerala                Thiruvananthapuram
12     Madhya Pradesh                            Bhopal
13        Maharashtra                         Mumbai[e]
14            Manipur                            Imphal
15          Meghalaya                          Shillong
16            Mizoram                            Aizawl
17           Nagaland                            Kohima
18             Odisha                       Bhubaneswar
19             Punjab                        Chandigarh
20          Rajasthan                            Jaipur
21             Sikkim                        Gangtok[f]
22         Tamil Nadu                        Chennai[g]
23          Telangana                         Hyderabad
24            Tripura                          Agartala
25      Uttar Pradesh                           Lucknow
26        Uttarakhand                          Dehradun
27        West Bengal                           Kolkata

                          Legislative capital Judicial capital  \
0                                   Amaravati        Amaravati
1                                    Itanagar         Guwahati
2                                      Dispur         Guwahati
3                                       Patna            Patna
4                                      Raipur         Bilaspur
5                                    Porvorim           Mumbai
6                                 Gandhinagar        Ahmedabad
7                                  Chandigarh       Chandigarh
8     Shimla (Summer) Dharamshala (Winter)[5]           Shimla
9                                      Ranchi           Ranchi
10                                  Bengaluru        Bengaluru
11                         Thiruvananthapuram         Kochi[6]
12                                     Bhopal         Jabalpur
13         Mumbai (Summer) Nagpur (Winter)[7]           Mumbai
14                                     Imphal           Imphal
15                                   Shillong         Shillong
16                                     Aizawl         Guwahati
17                                     Kohima         Guwahati
18                                Bhubaneswar          Cuttack
19                                 Chandigarh       Chandigarh
20                                     Jaipur          Jodhpur
21                                    Gangtok          Gangtok
22                                    Chennai          Chennai
23                                  Hyderabad        Hyderabad
24                                   Agartala         Agartala
25                                    Lucknow        Prayagraj
26  Bhararisain (summer)[9] Dehradun (winter)         Nainital
27                                    Kolkata          Kolkata

    Year of establishment            Former capital
0                    2014  Hyderabad[a] (1956–2014)
1                    1987                         —
2                    1972   Shillong[b] (1950–1972)
3                    1950                         —
4                    2000                         —
5                    1987                         —
6                    1960     Ahmedabad (1960–1970)
7                    1966                         —
8                    1971                         —
9                    2000                         —
10                   1956                         —
11                   1956                         —
12                   1956                         —
13                   1960                         —
14                   1972                         —
15                   1972                         —
16                   1987                         —
17                   1963                         —
18                   1950                         —
19                   1966                         —
20                   1950                         —
21                   1975                         —
22                   1956                         —
23                   2014                         —
24                   1972                         —
25                   1950                         —
26                   2000                         —
27                   1950                         —  ,                             Union Territory Administrative/ Executive capital  \
0               Andaman and Nicobar Islands                        Port Blair
1                                Chandigarh                        Chandigarh
2  Dadra and Nagar Haveli and Daman and Diu                             Daman
3                         Jammu and Kashmir                          Srinagar
4                                    Ladakh                               Leh
5                               Lakshadweep                         Kavaratti
6                                     Delhi                         New Delhi
7                                Puducherry                       Pondicherry

                    Legislative capital Judicial capital  \
0                                     –          Kolkata
1                                     –       Chandigarh
2                                     –           Mumbai
3  Srinagar (summer) Jammu (winter)[10]         Srinagar
4                                     –         Srinagar
5                                     –            Kochi
6                             New Delhi        New Delhi
7                           Pondicherry          Chennai

   Year of establishment
0                   1956
1                   1966
2                   2020
3                   2019
4                   2019
5                   1956
6                   1956
7                   1951  ,   vteState and Union Territory capitals of India  \
0                                 Administrative
1                                    Legislative
2                                       Judicial

    vteState and Union Territory capitals of India.1
0  Agartala Aizawl Amaravati Bengaluru Bhopal Bhu...
1  Agartala Aizawl Amaravati Bengaluru (summer) B...
2  Agartala Ahmedabad Amaravati Bengaluru Bilaspu...  ]

In [44]:
html[0]

    States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1                                                vte

In [45]:
type(html[1])   # dataframe

pandas.core.frame.DataFrame

In [42]:
html[1]

,State,Administrative/ Executive capital,Legislative capital,Judicial capital,Year of establishment,Former capital
0,Andhra Pradesh,Amaravati,Amaravati,Amaravati,2014,Hyderabad[a] (1956–2014)
1,Arunachal Pradesh,Itanagar,Itanagar,Guwahati,1987,—
2,Assam,Dispur,Dispur,Guwahati,1972,Shillong[b] (1950–1972)
3,Bihar,Patna,Patna,Patna,1950,—
4,Chhattisgarh,Raipur[c],Raipur,Bilaspur,2000,—
5,Goa,Panaji[d],Porvorim,Mumbai,1987,—
6,Gujarat,Gandhinagar,Gandhinagar,Ahmedabad,1960,Ahmedabad (1960–1970)
7,Haryana,Chandigarh,Chandigarh,Chandigarh,1966,—
8,Himachal Pradesh,Shimla,Shimla (Summer) Dharamshala (Winter)[5],Shimla,1971,—
9,Jharkhand,Ranchi,Ranchi,Ranchi,2000,—
10,Karnataka,Bengaluru,Bengaluru,Bengaluru,1956,—
11,Kerala,Thiruvananthapuram,Thiruvananthapuram,Kochi[6],1956,—
12,Madhya Pradesh,Bhopal,Bhopal,Jabalpur,1956,—
13,Maharashtra,Mumbai[e],Mumbai (Summer) Nagpur (Winter)[7],Mumbai,1960,—
14,Manipur,Imphal,Imphal,Imphal,1972,—
15,Meghalaya,Shillong,Shillong,Shillong,1972,—
16,Mizoram,Aizawl,Aizawl,Guwahati,1987,—
17,Nagaland,Kohima,Kohima,Guwahati,1963,—
18,Odisha,Bhubaneswar,Bhubaneswar,Cuttack,1950,—
19,Punjab,Chandigarh,Chandigarh,Chandigarh,1966,—
20,Rajasthan,Jaipur,Jaipur,Jodhpur,1950,—
21,Sikkim,Gangtok[f],Gangtok,Gangtok,1975,—
22,Tamil Nadu,Chennai[g],Chennai,Chennai,1956,—
23,Telangana,Hyderabad,Hyderabad,Hyderabad,2014,—
24,Tripura,Agartala,Agartala,Agartala,1972,—
25,Uttar Pradesh,Lucknow,Lucknow,Prayagraj,1950,—
26,Uttarakhand,Dehradun,Bhararisain (summer)[9] Dehradun (winter),Nainital,2000,—
27,West Bengal,Kolkata,Kolkata,Kolkata,1950,—

In [43]:
html[2]

,Union Territory,Administrative/ Executive capital,Legislative capital,Judicial capital,Year of establishment
0,Andaman and Nicobar Islands,Port Blair,–,Kolkata,1956
1,Chandigarh,Chandigarh,–,Chandigarh,1966
2,Dadra and Nagar Haveli and Daman and Diu,Daman,–,Mumbai,2020
3,Jammu and Kashmir,Srinagar,Srinagar (summer) Jammu (winter)[10],Srinagar,2019
4,Ladakh,Leh,–,Srinagar,2019
5,Lakshadweep,Kavaratti,–,Kochi,1956
6,Delhi,New Delhi,New Delhi,New Delhi,1956
7,Puducherry,Pondicherry,Pondicherry,Chennai,1951

In [57]:
html = pd.read_html('https://en.wikipedia.org/wiki/Economy_of_India' , storage_options={'User-Agent': 'Mozilla/5.0'} , match='Year')

In [58]:
html

[    Year  GDP (in Bil. US$PPP) GDP per capita (in US$ PPP)  \
 0   1980                 366.4                       526.9
 1   1981                 431.5                       603.2
 2   1982                 474.1                       647.5
 3   1983                 528.6                       705.3
 4   1984                 568.6                       741.4
 5   1985                 617.4                       787.1
 6   1986                 659.9                       822.8
 7   1987                 703.0                       857.7
 8   1988                 797.9                       952.7
 9   1989                 878.5                      1027.0
 10  1990                 961.8                      1101.3
 11  1991                1004.8                      1127.4
 12  1992                1084.1                      1192.2
 13  1993                1162.5                      1253.5
 14  1994                1266.4                      1339.2
 15  1995                1390.8                      1442.9
 16  1996                1523.2                      1550.6
 17  1997                1612.3                      1610.8
 18  1998                1731.2                      1698.1
 19  1999                1904.2                      1834.4
 20  2000                2024.7                      1916.3
 21  2001                2172.7                      2021.1
 22  2002                2292.8                      2097.1
 23  2003                2523.8                      2270.6
 24  2004                2795.0                      2474.2
 25  2005                3066.0                     2.655.3
 26  2006                3415.2                      2913.1
 27  2007                3776.5                      3174.3
 28  2008                3968.1                      3288.3
 29  2009                4306.4                      3519.4
 30  2010                4729.2                      3812.0
 31  2011                5079.8                      4039.1
 32  2012                5456.7                      4281.4
 33  2013                5904.0                      4572.7
 34  2014                6451.9                      4935.5
 35  2015                7032.5                      5316.1
 36  2016                7685.5                      5741.2
 37  2017                8354.7                      6169.5
 38  2018                9230.8                      6742.7
 39  2019                9932.8                      7181.5
 40  2020                9771.0                       69974
 41  2021               11384.4                      8088.0
 42  2022               13048.1                      9207.2
 43  2023               14619.8                     10233.4
 44  2024               16020.0                     11111.7
 45  2025               17364.8                     11937.8
 46  2026               18831.4                     12834.6
 47  2027               20420.1                     13801.3
 48  2028               22143.7                     14844.9
 49  2029               24015.1                     15973.1

     GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
 0                      189.4                            271.0
 1                      196.5                            274.7
 2                      203.5                            278.0
 3                      222.0                            296.3
 4                      215.6                            281.1
 5                      237.6                            302.9
 6                      252.8                            315.2
 7                      283.8                            346.2
 8                      299.6                            357.8
 9                      301.2                            352.2
 10                     326.6                            374.0
 11                     274.8                            308.4
 12                     293.3                            322.5
 13                     284.2                            306.4
 14                     333.0                            352.2
 15                     366.6                            380.3
 16                     399.8                            407.0
 17                     423.2                            422.8
 18                     428.8                            420.6
 19                     466.9                            449.8
 20                     476.6                            451.1
 21                     494.0                            459.5
 22                     524.0                            479.2
 23                     618.4                            556.3
 24                     721.6                            638.8
 25                     834.2                            726.9
 26                     949.1                            814.4
 27                    1238.7                           1046.9
 28                    1224.1                           1019.5
 29                    1365.4                           1121.2
 30                    1708.5                           1384.2
 31                    1823.1                           1458.1
 32                    1827.6                           1443.9
 33                    1856.7                           1449.6
 34                    2039.1                           1573.9
 35                    2103.6                           1605.6
 36                    2294.8                           1732.6
 37                    2702.9                           1958.0
 38                    2702.9                           1974.4
 39                    2835.6                           2050.2
 40                    2674.8                           1915.6
 41                    3167.3                           2250.1
 42                    3389.7                           2391.9
 43                    3567.5                           2497.2
 44                    3889.1                           2697.6
 45                    4271.9                           2936.8
 46                    4710.4                           3210.4
 47                    5193.5                           3510.1
 48                    5723.2                           3836.8
 49                    6307.2                           4195.1

    GDP growth (real) Inflation rate (in Percent) Unemployment (in Percent)  \
 0              6.74%                       11.3%                       NaN
 1              6.01%                       12.7%                       NaN
 2               3.5%                        7.7%                       NaN
 3               7.3%                       12.6%                       NaN
 4               3.8%                        5.2%                       NaN
 5               5.3%                  5.56%[217]                       NaN
 6               4.8%                   7.8%[218]                       NaN
 7               4.0%                        9.1%                       NaN
 8             10.18%                        7.2%                       NaN
 9               5.9%                        4.6%                       NaN
 10              5.5%                       11.2%                       NaN
 11              1.1%                       13.5%                      6.8%
 12              5.5%                        9.9%                      6.8%
 13              4.8%                        7.3%                      6.8%
 14              6.7%                       10.3%                      6.8%
 15              7.6%                       10.0%                        7%
 16              7.6%                        9.4%                      7.2%
 17              4.1%                        6.8%                      7.3%
 18              6.2%                       13.1%                      7.5%
 19              8.5%                        5.7%                      7.7%
 20              4.0%                        3.8%                      7.8%
 21              4.9%                        4.3%                        8%
 22              3.9%                        4.0%                      8.2%
 23              7.9%                        3.9%                      8.4%
 24              7.8%                        3.8%                      8.5%
 25              9.3%                        4.4%                      8.7%
 26              9.3%                        6.7%                      8.6%
 27             10.3%                        6.2%                      8.5%
 28              3.9%                        9.1%                      8.5%
 29              7.9%                       12.3%                      8.4%
 30              8.5%                       10.5%                      8.3%
 31              6.6%                        9.5%                      8.2%
 32              5.5%                       10.0%                      8.1%
 33              6.4%                        9.4%                      8.1%
 34              7.4%                        5.8%                        8%
 35              8.0%                        4.9%                      7.9%
 36              8.3%                        4.5%                      7.8%
 37              6.8%                        3.6%                      7.7%
 38              6.5%                        3.4%                      7.7%
 39              4.2%                        4.8%                      6.5%
 40             -5.8%                        6.1%                      7.9%
 41         9.7%[219]                        5.5%                      6.4%
 42              7.6%                        6.7%                      4.8%
 43              9.2%                        5.5%                      4.7%
 44              7.0%                        4.6%                       NaN
 45              6.5%                        4.1%                       NaN
 46              6.5%                        4.1%                       NaN
 47              6.5%                        4.0%                       NaN
 48              6.5%                        4.0%                       NaN
 49              6.5%                        4.0%                       NaN

    Government debt (in % of GDP)
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 5                            NaN
 6                            NaN
 7                            NaN
 8                            NaN
 9                            NaN
 10                           NaN
 11                         75.3%
 12                         77.4%
 13                         77.0%
 14                         73.5%
 15                         69.7%
 16                         66.0%
 17                         67.8%
 18                         68.1%
 19                         70.0%
 20                         73.6%
 21                         78.7%
 22                         82.9%
 23                         84.4%
 24                         83.4%
 25                         81.0%
 26                         77.2%
 27                         74.1%
 28                         72.8%
 29                         71.5%
 30                         66.4%
 31                         68.6%
 32                         68.0%
 33                         67.7%
 34                         67.1%
 35                         69.0%
 36                         68.9%
 37                         69.7%
 38                         70.4%
 39                         75.0%
 40                         88.5%
 41                         83.7%
 42                         81.0%
 43                         81.9%
 44                         83.0%
 45                         82.6%
 46                         81.8%
 47                         80.7%
 48                         80.0%
 49                         78.4%  ,
     Year INR₹ per US$ (annual average)[482]  \
 0   1947                               3.31
 1   1950                               4.76
 2   1967                               7.50
 3   1975                             9.4058
 4   1980                               7.88
 5   1985                             12.364
 6   1987                               —N/a
 7   1990                            17.4992
 8   1995                            32.4198
 9   2000                            44.9401
 10  2005                            44.1000
 11  2010                            45.7393
 12  2015                              64.05
 13  2016                              67.09
 14  2017                              64.14
 15  2018                              69.71
 16  2019                             70.394
 17  2020                              72.97
 18  2021                              74.98
 19  2022                              81.35
 20  2023                              82.58
 21  2024                              83.20
 22  2025                              86.46

    INR₹ per Pound(£) (annual average)[483]
 0                                    13.33
 1                                     —N/a
 2                                    17.76
 3                                     —N/a
 4                                     —N/a
 5                                     —N/a
 6                                    21.18
 7                                    31.07
 8                                    51.17
 9                                    67.99
 10                                   80.15
 11                                   70.65
 12                                 98.0101
 13                                   90.72
 14                                   87.56
 15                                   98.51
 16                                   95.06
 17                                  100.05
 18                                  101.56
 19                                   96.23
 20                                  100.95
 21                                  104.41
 22                                  107.38  ,
          Year  Total Trade (in USD billion)  Exports (in USD billion)  \
 0        2024                       1631.48                    776.68
 1        2023                       1662.36                    770.18
 2   2022[497]                       1436.59                    676.53
 3        2021                       1032.00                    420.00
 4        2020                        781.50                    314.31
 5        2019                        844.14                    330.07
 6        2018                        769.10                    303.52
 7        2017                        660.10                    275.80
 8        2016                        643.30                    262.30
 9        2015                        758.20                    310.30
 10       2014                        781.10                    318.20
 11       2013                        780.70                    313.20
 12       2012                        798.80                    298.40
 13       2011                        760.80                    299.40
 14       2010                        528.10                    201.10
 15       2009                        442.50                    168.20
 16       2008                        481.90                    176.40
 17       2007                        212.90                    112.00
 18       2006                        189.33                     76.23
 19       2005                        158.51                     69.18
 20       2004                        131.39                     57.24
 21       2003                        109.90                     48.30
 22       2002                         98.30                     44.50
 23       2001                         97.00                     42.50
 24       2000                        103.90                     43.10
 25       1999                         86.50                     36.30

     Imports (in USD billion)  Trade Deficit  (in USD billion)
 0                     854.80                           -78.12
 1                     892.18                          -122.00
 2                     760.06                           -83.53
 3                     612.00                          -192.00
 4                     467.19                          -158.88
 5                     514.07                          -184.00
 6                     465.58                          -162.05
 7                     384.30                          -108.50
 8                     381.00                          -118.70
 9                     447.90                          -137.60
 10                    462.90                          -144.70
 11                    467.50                          -154.30
 12                    500.40                          -202.00
 13                    461.40                          -162.00
 14                    327.00                          -125.90
 15                    274.30                          -106.10
 16                    305.50                          -129.10
 17                    100.90                            11.10
 18                    113.10                           -36.87
 19                     89.33                           -20.15
 20                     74.15                           -16.91
 21                     61.60                           -13.30
 22                     53.80                            -9.30
 23                     54.50                           -12.00
 24                     60.80                           -17.70
 25                     50.20                           -13.90  ,
                             Links to related articles  \
 0   vteEconomy of Asia Sovereign states Afghanista...
 1                                  vteEconomy of Asia
 2                                    Sovereign states
 3                     States with limited recognition
 4                  Dependencies and other territories
 ..                                                ...
 88                            Ministerial Conferences
 89                                             People
 90                                            Members
 91                                     European Union
 92  Special administrative regions of the People's...

                           Links to related articles.1 Unnamed: 2
 0   vteEconomy of Asia Sovereign states Afghanista...        NaN
 1                                  vteEconomy of Asia        NaN
 2   Afghanistan Armenia Azerbaijan Bahrain Banglad...        NaN
 3       Abkhazia Northern Cyprus South Ossetia Taiwan        NaN
 4   British Indian Ocean Territory Christmas Islan...        NaN
 ..                                                ...        ...
 88  1st (1996) 2nd (1998) 3rd (1999) 4th (2001) 5t...        NaN
 89  Ngozi Okonjo-Iweala (Director-General) Roberto...        NaN
 90  Afghanistan Albania Algeria Angola Antigua and...        NaN
 91  Austria Belgium Bulgaria Croatia Cyprus Czech ...        NaN
 92  Special administrative regions of the People's...        NaN

 [93 rows x 3 columns],
                                       vteIndia topics  \
 0   HistoryOverviews Timeline Years Astronomy Clot...
 1                                             History
 2   Overviews Timeline Years Astronomy Clothing Co...
 3                                           Overviews
 4                                             Ancient
 5                                     Middle Kingdoms
 6                                         Middle Ages
 7                                        Early Modern
 8                                         Late modern
 9                                            Republic
 10                                       Contemporary
 11  GeographyGeology Fossil Parks Geology of India...
 12                                          Geography
 13  Geology Fossil Parks Geology of India Indian P...

In [59]:
html[0]

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (in % of GDP)
0,1980,366.4,526.9,189.4,271.0,6.74%,11.3%,NaN,NaN
1,1981,431.5,603.2,196.5,274.7,6.01%,12.7%,NaN,NaN
2,1982,474.1,647.5,203.5,278.0,3.5%,7.7%,NaN,NaN
3,1983,528.6,705.3,222.0,296.3,7.3%,12.6%,NaN,NaN
4,1984,568.6,741.4,215.6,281.1,3.8%,5.2%,NaN,NaN
5,1985,617.4,787.1,237.6,302.9,5.3%,5.56%[217],NaN,NaN
6,1986,659.9,822.8,252.8,315.2,4.8%,7.8%[218],NaN,NaN
7,1987,703.0,857.7,283.8,346.2,4.0%,9.1%,NaN,NaN
8,1988,797.9,952.7,299.6,357.8,10.18%,7.2%,NaN,NaN
9,1989,878.5,1027.0,301.2,352.2,5.9%,4.6%,NaN,NaN
10,1990,961.8,1101.3,326.6,374.0,5.5%,11.2%,NaN,NaN
11,1991,1004.8,1127.4,274.8,308.4,1.1%,13.5%,6.8%,75.3%
12,1992,1084.1,1192.2,293.3,322.5,5.5%,9.9%,6.8%,77.4%
13,1993,1162.5,1253.5,284.2,306.4,4.8%,7.3%,6.8%,77.0%
14,1994,1266.4,1339.2,333.0,352.2,6.7%,10.3%,6.8%,73.5%
15,1995,1390.8,1442.9,366.6,380.3,7.6%,10.0%,7%,69.7%
16,1996,1523.2,1550.6,399.8,407.0,7.6%,9.4%,7.2%,66.0%
17,1997,1612.3,1610.8,423.2,422.8,4.1%,6.8%,7.3%,67.8%
18,1998,1731.2,1698.1,428.8,420.6,6.2%,13.1%,7.5%,68.1%
19,1999,1904.2,1834.4,466.9,449.8,8.5%,5.7%,7.7%,70.0%
20,2000,2024.7,1916.3,476.6,451.1,4.0%,3.8%,7.8%,73.6%
21,2001,2172.7,2021.1,494.0,459.5,4.9%,4.3%,8%,78.7%
22,2002,2292.8,2097.1,524.0,479.2,3.9%,4.0%,8.2%,82.9%
23,2003,2523.8,2270.6,618.4,556.3,7.9%,3.9%,8.4%,84.4%
24,2004,2795.0,2474.2,721.6,638.8,7.8%,3.8%,8.5%,83.4%
25,2005,3066.0,2.655.3,834.2,726.9,9.3%,4.4%,8.7%,81.0%
26,2006,3415.2,2913.1,949.1,814.4,9.3%,6.7%,8.6%,77.2%
27,2007,3776.5,3174.3,1238.7,1046.9,10.3%,6.2%,8.5%,74.1%
28,2008,3968.1,3288.3,1224.1,1019.5,3.9%,9.1%,8.5%,72.8%
29,2009,4306.4,3519.4,1365.4,1121.2,7.9%,12.3%,8.4%,71.5%
30,2010,4729.2,3812.0,1708.5,1384.2,8.5%,10.5%,8.3%,66.4%
31,2011,5079.8,4039.1,1823.1,1458.1,6.6%,9.5%,8.2%,68.6%
32,2012,5456.7,4281.4,1827.6,1443.9,5.5%,10.0%,8.1%,68.0%
33,2013,5904.0,4572.7,1856.7,1449.6,6.4%,9.4%,8.1%,67.7%
34,2014,6451.9,4935.5,2039.1,1573.9,7.4%,5.8%,8%,67.1%
35,2015,7032.5,5316.1,2103.6,1605.6,8.0%,4.9%,7.9%,69.0%
36,2016,7685.5,5741.2,2294.8,1732.6,8.3%,4.5%,7.8%,68.9%
37,2017,8354.7,6169.5,2702.9,1958.0,6.8%,3.6%,7.7%,69.7%
38,2018,9230.8,6742.7,2702.9,1974.4,6.5%,3.4%,7.7%,70.4%
39,2019,9932.8,7181.5,2835.6,2050.2,4.2%,4.8%,6.5%,75.0%
40,2020,9771.0,69974,2674.8,1915.6,-5.8%,6.1%,7.9%,88.5%
41,2021,11384.4,8088.0,3167.3,2250.1,9.7%[219],5.5%,6.4%,83.7%
42,2022,13048.1,9207.2,3389.7,2391.9,7.6%,6.7%,4.8%,81.0%
43,2023,14619.8,10233.4,3567.5,2497.2,9.2%,5.5%,4.7%,81.9%
44,2024,16020.0,11111.7,3889.1,2697.6,7.0%,4.6%,NaN,83.0%
45,2025,17364.8,11937.8,4271.9,2936.8,6.5%,4.1%,NaN,82.6%
46,2026,18831.4,12834.6,4710.4,3210.4,6.5%,4.1%,NaN,81.8%
47,2027,20420.1,13801.3,5193.5,3510.1,6.5%,4.0%,NaN,80.7%
48,2028,22143.7,14844.9,5723.2,3836.8,6.5%,4.0%,NaN,80.0%
49,2029,24015.1,15973.1,6307.2,4195.1,6.5%,4.0%,NaN,78.4%

In [60]:
html[2]

,Year,Total Trade (in USD billion),Exports (in USD billion),Imports (in USD billion),Trade Deficit (in USD billion)
0,2024,1631.48,776.68,854.80,-78.12
1,2023,1662.36,770.18,892.18,-122.00
2,2022[497],1436.59,676.53,760.06,-83.53
3,2021,1032.00,420.00,612.00,-192.00
4,2020,781.50,314.31,467.19,-158.88
5,2019,844.14,330.07,514.07,-184.00
6,2018,769.10,303.52,465.58,-162.05
7,2017,660.10,275.80,384.30,-108.50
8,2016,643.30,262.30,381.00,-118.70
9,2015,758.20,310.30,447.90,-137.60
10,2014,781.10,318.20,462.90,-144.70
11,2013,780.70,313.20,467.50,-154.30
12,2012,798.80,298.40,500.40,-202.00
13,2011,760.80,299.40,461.40,-162.00
14,2010,528.10,201.10,327.00,-125.90
15,2009,442.50,168.20,274.30,-106.10
16,2008,481.90,176.40,305.50,-129.10
17,2007,212.90,112.00,100.90,11.10
18,2006,189.33,76.23,113.10,-36.87
19,2005,158.51,69.18,89.33,-20.15
20,2004,131.39,57.24,74.15,-16.91
21,2003,109.90,48.30,61.60,-13.30
22,2002,98.30,44.50,53.80,-9.30
23,2001,97.00,42.50,54.50,-12.00
24,2000,103.90,43.10,60.80,-17.70
25,1999,86.50,36.30,50.20,-13.90

In [68]:
html = pd.read_html('https://en.wikipedia.org/wiki/List_of_prime_ministers_of_India' , storage_options={'User-Agent': 'Mozilla/5.0'} ,match='Portrait')

In [69]:
html

[    Portrait                    Name (born – died) Constituency  \
 0        NaN  Jawaharlal Nehru (1889–1964) MP for United Pro...
 1        NaN  Jawaharlal Nehru (1889–1964) MP for United Pro...
 2        NaN  Jawaharlal Nehru (1889–1964) MP for United Pro...
 3        NaN  Jawaharlal Nehru (1889–1964) MP for United Pro...
 4        NaN  Jawaharlal Nehru (1889–1964) MP for United Pro...
 5        NaN  Gulzarilal Nanda (acting) (1898–1998) MP for S...
 6        NaN   Lal Bahadur Shastri (1904–1966) MP for Allahabad
 7        NaN  Gulzarilal Nanda (acting) (1898–1998) MP for S...
 8        NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 9        NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 10       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 11       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 12       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 13       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 14       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 15       NaN  Indira Gandhi (1917–1984) MP for Uttar Pradesh...
 16       NaN             Morarji Desai (1896–1995) MP for Surat
 17       NaN             Morarji Desai (1896–1995) MP for Surat
 18       NaN            Charan Singh (1902–1987) MP for Baghpat
 19       NaN             Indira Gandhi (1917–1984) MP for Medak
 20       NaN             Indira Gandhi (1917–1984) MP for Medak
 21       NaN             Rajiv Gandhi (1944–1991) MP for Amethi
 22       NaN             Rajiv Gandhi (1944–1991) MP for Amethi
 23       NaN            V. P. Singh (1931–2008) MP for Fatehpur
 24       NaN          Chandra Shekhar (1927–2007) MP for Ballia
 25       NaN     P. V. Narasimha Rao (1921–2004) MP for Nandyal
 26       NaN     P. V. Narasimha Rao (1921–2004) MP for Nandyal
 27       NaN    Atal Bihari Vajpayee (1924–2018) MP for Lucknow
 28       NaN  H. D. Deve Gowda (born 1933) MP for Karnataka ...
 29       NaN  Inder Kumar Gujral (1919–2012) MP for Bihar (R...
 30       NaN  Inder Kumar Gujral (1919–2012) MP for Bihar (R...
 31       NaN    Atal Bihari Vajpayee (1924–2018) MP for Lucknow
 32       NaN    Atal Bihari Vajpayee (1924–2018) MP for Lucknow
 33       NaN    Atal Bihari Vajpayee (1924–2018) MP for Lucknow
 34       NaN  Manmohan Singh (1932–2024) MP for Assam (Rajya...
 35       NaN  Manmohan Singh (1932–2024) MP for Assam (Rajya...
 36       NaN  Manmohan Singh (1932–2024) MP for Assam (Rajya...
 37       NaN  Manmohan Singh (1932–2024) MP for Assam (Rajya...
 38       NaN          Narendra Modi (born 1950) MP for Varanasi
 39       NaN          Narendra Modi (born 1950) MP for Varanasi
 40       NaN          Narendra Modi (born 1950) MP for Varanasi
 41       NaN          Narendra Modi (born 1950) MP for Varanasi
 42       NaN          Narendra Modi (born 1950) MP for Varanasi

    Age when assumed office Term of office Duration in years and days  \
 0        57 years 274 days                            15 August 1947
 1        57 years 274 days                            15 August 1947
 2        57 years 274 days                            15 August 1947
 3        57 years 274 days                            15 August 1947
 4        57 years 274 days                            15 August 1947
 5       65 years, 328 days                               27 May 1964
 6        59 years 251 days                               9 June 1964
 7       67 years, 191 days                           11 January 1966
 8        48 years, 66 days                           24 January 1966
 9        48 years, 66 days                           24 January 1966
 10       48 years, 66 days                           24 January 1966
 11       48 years, 66 days                           24 January 1966
 12       48 years, 66 days                           24 January 1966
 13       48 years, 66 days                           24 January 1966
 14       48 years, 66 days                           24 January 1966
 15       48 years, 66 days                           24 January 1966
 16       81 years, 24 days                             24 March 1977
 17       81 years, 24 days                             24 March 1977
 18      76 years, 217 days                              28 July 1979
 19       62 years, 56 days                        14 January 1980[§]
 20       62 years, 56 days                        14 January 1980[§]
 21       40 years, 72 days                           31 October 1984
 22       40 years, 72 days                           31 October 1984
 23      58 years, 160 days                           2 December 1989
 24      63 years, 207 days                          10 November 1990
 25      69 years, 358 days                              21 June 1991
 26      69 years, 358 days                              21 June 1991
 27      71 years, 143 days                               16 May 1996
 28       63 years, 14 days                               1 June 1996
 29      77 years, 138 days                             21 April 1997
 30      77 years, 138 days                             21 April 1997
 31       73 years, 84 days                          19 March 1998[§]
 32       73 years, 84 days                          19 March 1998[§]
 33       73 years, 84 days                          19 March 1998[§]
 34      71 years, 239 days                               22 May 2004
 35      71 years, 239 days                               22 May 2004
 36      71 years, 239 days                               22 May 2004
 37      71 years, 239 days                               22 May 2004
 38      63 years, 251 days                               26 May 2014
 39      63 years, 251 days                               26 May 2014
 40      63 years, 251 days                               26 May 2014
 41      63 years, 251 days                               26 May 2014
 42      63 years, 251 days                               26 May 2014

    Term of office Duration in years and days.1  \
 0                               27 May 1964[†]
 1                               27 May 1964[†]
 2                               27 May 1964[†]
 3                               27 May 1964[†]
 4                               27 May 1964[†]
 5                             9 June 1964[DIS]
 6                           11 January 1966[†]
 7                         24 January 1966[DIS]
 8                           24 March 1977[DIS]
 9                           24 March 1977[DIS]
 10                          24 March 1977[DIS]
 11                          24 March 1977[DIS]
 12                          24 March 1977[DIS]
 13                          24 March 1977[DIS]
 14                          24 March 1977[DIS]
 15                          24 March 1977[DIS]
 16                           28 July 1979[RES]
 17                           28 July 1979[RES]
 18                        14 January 1980[RES]
 19                          31 October 1984[†]
 20                          31 October 1984[†]
 21                        2 December 1989[DIS]
 22                        2 December 1989[DIS]
 23                        10 November 1990[NC]
 24                           21 June 1991[RES]
 25                            16 May 1996[DIS]
 26                            16 May 1996[DIS]
 27                            1 June 1996[RES]
 28                          21 April 1997[RES]
 29                          19 March 1998[RES]
 30                          19 March 1998[RES]
 31                            22 May 2004[DIS]
 32                            22 May 2004[DIS]
 33                            22 May 2004[DIS]
 34                            26 May 2014[DIS]
 35                            26 May 2014[DIS]
 36                            26 May 2014[DIS]
 37                            26 May 2014[DIS]
 38                                   Incumbent
 39                                   Incumbent
 40                                   Incumbent
 41                                   Incumbent
 42                                   Incumbent

    Term of office Duration in years and days.2 Election  \
 0                            16 years 286 days        –
 1                            16 years 286 days        –
 2                            16 years 286 days  1951–52
 3                            16 years 286 days     1957
 4                            16 years 286 days     1962
 5                                      13 days        –
 6                             1 year, 216 days        –
 7                                      13 days        –
 8                            11 years, 59 days        –
 9                            11 years, 59 days     1967
 10                           11 years, 59 days     1967
 11                           11 years, 59 days     1967
 12                           11 years, 59 days     1967
 13                           11 years, 59 days     1971
 14                           11 years, 59 days     1971
 15                           11 years, 59 days     1971
 16                           2 years, 126 days     1977
 17                           2 years, 126 days     1977
 18                                    170 days        –
 19                           4 years, 291 days     1980
 20                           4 years, 291 days     1980
 21                            5 years, 32 days        –
 22                            5 years, 32 days     1984
 23                                    343 days     1989
 24                                    223 days        –
 25                           4 years, 330 days     1991
 26                           4 years, 330 days     1991
 27                                     16 days     1996
 28                                    324 days        –
 29                                    332 days        –
 30                                    332 days        –
 31                            6 years, 64 days     1998
 32                            6 years, 64 days     1999
 33                            6 years, 64 days     1999
 34                            10 years, 4 days     2004
 35                            10 years, 4 days     2004
 36                            10 years, 4 days     2009
 37                            10 years, 4 days     2009
 38                          11 years, 303 days     2014
 39                          11 years, 303 days     2014
 40                          11 years, 303 days     2019
 41                          11 years, 303 days     2019
 42                          11 years, 303 days     2024

                      Concurrent ministerial positions  Party  \
 0   External and Commonwealth AffairsDefence (1952...    NaN
 1   External and Commonwealth AffairsDefence (1952...    NaN
 2   External and Commonwealth AffairsDefence (1952...    NaN
 3   External and Commonwealth AffairsDefence (1952...    NaN
 4   External and Commonwealth AffairsDefence (1952...    NaN
 5           Home AffairsExternal AffairsAtomic Energy    NaN
 6                             External Affairs (1964)    NaN
 7   Minister of Home AffairsMinister of Atomic Energy    NaN
 8   External Affairs (1967–1969)Finance (1970)Home...    NaN
 9   External Affairs (1967–1969)Finance (1970)Home...    NaN
 10  External Affairs (1967–1969)Finance (1970)Home...    NaN
 11  External Affairs (1967–1969)Finance (1970)Home...    NaN
 12  External Affairs (1967–1969)Finance (1970)Home...    NaN
 13  External Affairs (1967–1969)Finance (1970)Home...    NaN
 14  External Affairs (1967–1969)Finance (1970)Home...    NaN
 15  External Affairs (1967–1969)Finance (1970)Home...    NaN
 16       Finance (1977, 1979)Home Affairs (1978–1979)    NaN
 17       Finance (1977, 1979)Home Affairs (1978–1979)    NaN
 18                                                NaN    NaN
 19         Defence (1980–1982)External Affairs (1984)    NaN
 20         Defence (1980–1982)External Affairs (1984)    NaN
 21  External Affairs (1984–1985, 1987–1988)Tourism...    NaN
 22  External Affairs (1984–1985, 1987–1988)Tourism...    NaN
 23  DefenceHuman Resource DevelopmentExternal Affa...    NaN
 24                            External Affairs (1990)    NaN
 25  Chemicals and Fertilizers (1991–1994)External ...    NaN
 26  Chemicals and Fertilizers (1991–1994)External ...    NaN
 27  Chemicals and FertilizersTextilesCommerce and ...    NaN
 28  Home Affairs (1996)Agriculture (1996)Textiles ...    NaN
 29  Personnel, Public Grievances and PensionsExter...    NaN
 30  Personnel, Public Grievances and PensionsExter...    NaN
 31  External Affairs (1998)Information and Broadca...    NaN
 32  External Affairs (1998)Information and Broadca...    NaN
 33  External Affairs (1998)Information and Broadca...    NaN
 34  Personnel, Public Grievances and PensionsAtomi...    NaN
 35  Personnel, Public Grievances and PensionsAtomi...    NaN
 36  Personnel, Public Grievances and PensionsAtomi...    NaN
 37  Personnel, Public Grievances and PensionsAtomi...    NaN
 38  Personnel, Public Grievances and PensionsAtomi...    NaN
 39  Personnel, Public Grievances and PensionsAtomi...    NaN
 40  Personnel, Public Grievances and PensionsAtomi...    NaN
 41  Personnel, Public Grievances and PensionsAtomi...    NaN
 42  Personnel, Public Grievances and PensionsAtomi...    NaN

                                               Party.1         Ministry  \
 0                            Indian National Congress          Nehru I
 1                            Indian National Congress          Nehru I
 2                            Indian National Congress         Nehru II
 3                            Indian National Congress        Nehru III
 4                            Indian National Congress         Nehru IV
 5                            Indian National Congress          Nanda I
 6                            Indian National Congress          Shastri
 7                            Indian National Congress         Nanda II
 8                            Indian National Congress         Indira I
 9                            Indian National Congress        Indira II
 10                           Indian National Congress        Indira II
 11                           Indian National Congress        Indira II
 12                           Indian National Congress        Indira II
 13                       Indian National Congress (R)       Indira III
 14                       Indian National Congress (R)       Indira III
 15                       Indian National Congress (R)       Indira III
 16                                       Janata Party            Desai
 17                                       Janata Party            Desai
 18                             Janata Party (Secular)           Charan
 19                       Indian National Congress (I)        Indira IV
 20                       Indian National Congress (I)              NaN
 21                       Indian National Congress (I)          Rajiv I
 22                       Indian National Congress (I)         Rajiv II
 23                                         Janata Dal       Vishwanath
 24                 Samajwadi Janata Party (Rashtriya)  Chandra Shekhar
 25                       Indian National Congress (I)              Rao
 26                       Indian National Congress (I)              Rao
 27                             Bharatiya Janata Party       Vajpayee I
 28                          Janata Dal (United Front)       Deve Gowda
 29                          Janata Dal (United Front)           Gujral
 30                          Janata Dal (United Front)           Gujral
 31  Bharatiya Janata Party (National Democratic Al...      Vajpayee II
 32  Bharatiya Janata Party (National Democratic Al...     Vajpayee III
 33  Bharatiya Janata Party (National Democratic Al...     Vajpayee III
 34  Indian National Congress (United Progressive A...       Manmohan I
 35  Indian National Congress (United Progressive A...       Manmohan I
 36  Indian National Congress (United Progressive A...      Manmohan II
 37  Indian National Congress (United Progressive A...      Manmohan II
 38  Bharatiya Janata Party (National Democratic Al...           Modi I
 39  Bharatiya Janata Party (National Democratic Al...           Modi I
 40  Bharatiya Janata Party (National Democratic Al...          Modi II
 41  Bharatiya Janata Party (National Democratic Al...          Modi II
 42  Bharatiya Janata Party (National Democratic Al...         Modi III

                    Head of State (Tenure)
 0              King George VI (1947–1950)
 1             Rajendra Prasad (1950–1962)
 2             Rajendra Prasad (1950–1962)
 3             Rajendra Prasad (1950–1962)
 4    Sarvepalli Radhakrishnan (1962–1967)
 5    Sarvepalli Radhakrishnan (1962–1967)
 6    Sarvepalli Radhakrishnan (1962–1967)
 7    Sarvepalli Radhakrishnan (1962–1967)
 8    Sarvepalli Radhakrishnan (1962–1967)
 9                Zakir Husain (1967–1969)
 10             V. V. Giri (1969) (acting)
 11  Mohammad Hidayatullah (1969) (acting)
 12                 V. V. Giri (1969–1974)
 13                 V. V. Giri (1969–1974)
 14       Fakhruddin Ali Ahmed (1974–1977)
 15            B. D. Jatti (1977) (acting)
 16            B. D. Jatti (1977) (acting)
 17       Neelam Sanjiva Reddy (1977–1982)
 18       Neelam Sanjiva Reddy (1977–1982)
 19       Neelam Sanjiva Reddy (1977–1982)
 20                Zail Singh  (1982-1987)
 21                Zail Singh  (1982-1987)
 22     Ramaswamy Venkataraman (1987–1992)
 23     Ramaswamy Venkataraman (1987–1992)
 24     Ramaswamy Venkataraman (1987–1992)
 25     Ramaswamy Venkataraman (1987–1992)
 26       Shankar Dayal Sharma (1992–1997)
 27       Shankar Dayal Sharma (1992–1997)
 28       Shankar Dayal Sharma (1992–1997)
 29       Shankar Dayal Sharma (1992–1997)
 30            K. R. Narayanan (1997–2002)
 31            K. R. Narayanan (1997–2002)
 32            K. R. Narayanan (1997–2002)
 33       A. P. J. Abdul Kalam (2002–2007)
 34       A. P. J. Abdul Kalam (2002–2007)
 35             Pratibha Patil (2007–2012)
 36             Pratibha Patil (2007–2012)
 37           Pranab Mukherjee (2012–2017)
 38           Pranab Mukherjee (2012–2017)
 39            Ram Nath Kovind (2017–2022)
 40            Ram Nath Kovind (2017–2022)
 41          Droupadi Murmu (2022–present)
 42          Droupadi Murmu (2022–present)  ]

In [66]:
html[0]

,Portrait,Name (born – died) Constituency,Age when assumed office,Term of office Duration in years and days,Term of office Duration in years and days.1,Term of office Duration in years and days.2,Election,Concurrent ministerial positions,Party,Party.1,Ministry,Head of State (Tenure)
0,NaN,Jawaharlal Nehru (1889–1964) MP for United Pro...,57 years 274 days,15 August 1947,27 May 1964[†],16 years 286 days,–,External and Commonwealth AffairsDefence (1952...,NaN,Indian National Congress,Nehru I,King George VI (1947–1950)
1,NaN,Jawaharlal Nehru (1889–1964) MP for United Pro...,57 years 274 days,15 August 1947,27 May 1964[†],16 years 286 days,–,External and Commonwealth AffairsDefence (1952...,NaN,Indian National Congress,Nehru I,Rajendra Prasad (1950–1962)
2,NaN,Jawaharlal Nehru (1889–1964) MP for United Pro...,57 years 274 days,15 August 1947,27 May 1964[†],16 years 286 days,1951–52,External and Commonwealth AffairsDefence (1952...,NaN,Indian National Congress,Nehru II,Rajendra Prasad (1950–1962)
3,NaN,Jawaharlal Nehru (1889–1964) MP for United Pro...,57 years 274 days,15 August 1947,27 May 1964[†],16 years 286 days,1957,External and Commonwealth AffairsDefence (1952...,NaN,Indian National Congress,Nehru III,Rajendra Prasad (1950–1962)
4,NaN,Jawaharlal Nehru (1889–1964) MP for United Pro...,57 years 274 days,15 August 1947,27 May 1964[†],16 years 286 days,1962,External and Commonwealth AffairsDefence (1952...,NaN,Indian National Congress,Nehru IV,Sarvepalli Radhakrishnan (1962–1967)
5,NaN,Gulzarilal Nanda (acting) (1898–1998) MP for S...,"65 years, 328 days",27 May 1964,9 June 1964[DIS],13 days,–,Home AffairsExternal AffairsAtomic Energy,NaN,Indian National Congress,Nanda I,Sarvepalli Radhakrishnan (1962–1967)
6,NaN,Lal Bahadur Shastri (1904–1966) MP for Allahabad,59 years 251 days,9 June 1964,11 January 1966[†],"1 year, 216 days",–,External Affairs (1964),NaN,Indian National Congress,Shastri,Sarvepalli Radhakrishnan (1962–1967)
7,NaN,Gulzarilal Nanda (acting) (1898–1998) MP for S...,"67 years, 191 days",11 January 1966,24 January 1966[DIS],13 days,–,Minister of Home AffairsMinister of Atomic Energy,NaN,Indian National Congress,Nanda II,Sarvepalli Radhakrishnan (1962–1967)
8,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",–,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress,Indira I,Sarvepalli Radhakrishnan (1962–1967)
9,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1967,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress,Indira II,Zakir Husain (1967–1969)
10,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1967,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress,Indira II,V. V. Giri (1969) (acting)
11,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1967,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress,Indira II,Mohammad Hidayatullah (1969) (acting)
12,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1967,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress,Indira II,V. V. Giri (1969–1974)
13,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1971,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress (R),Indira III,V. V. Giri (1969–1974)
14,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1971,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress (R),Indira III,Fakhruddin Ali Ahmed (1974–1977)
15,NaN,Indira Gandhi (1917–1984) MP for Uttar Pradesh...,"48 years, 66 days",24 January 1966,24 March 1977[DIS],"11 years, 59 days",1971,External Affairs (1967–1969)Finance (1970)Home...,NaN,Indian National Congress (R),Indira III,B. D. Jatti (1977) (acting)
16,NaN,Morarji Desai (1896–1995) MP for Surat,"81 years, 24 days",24 March 1977,28 July 1979[RES],"2 years, 126 days",1977,"Finance (1977, 1979)Home Affairs (1978–1979)",NaN,Janata Party,Desai,B. D. Jatti (1977) (acting)
17,NaN,Morarji Desai (1896–1995) MP for Surat,"81 years, 24 days",24 March 1977,28 July 1979[RES],"2 years, 126 days",1977,"Finance (1977, 1979)Home Affairs (1978–1979)",NaN,Janata Party,Desai,Neelam Sanjiva Reddy (1977–1982)
18,NaN,Charan Singh (1902–1987) MP for Baghpat,"76 years, 217 days",28 July 1979,14 January 1980[RES],170 days,–,NaN,NaN,Janata Party (Secular),Charan,Neelam Sanjiva Reddy (1977–1982)
19,NaN,Indira Gandhi (1917–1984) MP for Medak,"62 years, 56 days",14 January 1980[§],31 October 1984[†],"4 years, 291 days",1980,Defence (1980–1982)External Affairs (1984),NaN,Indian National Congress (I),Indira IV,Neelam Sanjiva Reddy (1977–1982)
20,NaN,Indira Gandhi (1917–1984) MP for Medak,"62 years, 56 days",14 January 1980[§],31 October 1984[†],"4 years, 291 days",1980,Defence (1980–1982)External Affairs (1984),NaN,Indian National Congress (I),NaN,Zail Singh (1982-1987)
21,NaN,Rajiv Gandhi (1944–1991) MP for Amethi,"40 years, 72 days",31 October 1984,2 December 1989[DIS],"5 years, 32 days",–,"External Affairs (1984–1985, 1987–1988)Tourism...",NaN,Indian National Congress (I),Rajiv I,Zail Singh (1982-1987)
22,NaN,Rajiv Gandhi (1944–1991) MP for Amethi,"40 years, 72 days",31 October 1984,2 December 1989[DIS],"5 years, 32 days",1984,"External Affairs (1984–1985, 1987–1988)Tourism...",NaN,Indian National Congress (I),Rajiv II,Ramaswamy Venkataraman (1987–1992)
23,NaN,V. P. Singh (1931–2008) MP for Fatehpur,"58 years, 160 days",2 December 1989,10 November 1990[NC],343 days,1989,DefenceHuman Resource DevelopmentExternal Affa...,NaN,Janata Dal,Vishwanath,Ramaswamy Venkataraman (1987–1992)
24,NaN,Chandra Shekhar (1927–2007) MP for Ballia,"63 years, 207 days",10 November 1990,21 June 1991[RES],223 days,–,External Affairs (1990),NaN,Samajwadi Janata Party (Rashtriya),Chandra Shekhar,Ramaswamy Venkataraman (1987–1992)
25,NaN,P. V. Narasimha Rao (1921–2004) MP for Nandyal,"69 years, 358 days",21 June 1991,16 May 1996[DIS],"4 years, 330 days",1991,Chemicals and Fertilizers (1991–1994)External ...,NaN,Indian National Congress (I),Rao,Ramaswamy Venkataraman (1987–1992)
26,NaN,P. V. Narasimha Rao (1921–2004) MP for Nandyal,"69 years, 358 days",21 June 1991,16 May 1996[DIS],"4 years, 330 days",1991,Chemicals and Fertilizers (1991–1994)External ...,NaN,Indian National Congress (I),Rao,Shankar Dayal Sharma (1992–1997)
27,NaN,Atal Bihari Vajpayee (1924–2018) MP for Lucknow,"71 years, 143 days",16 May 1996,1 June 1996[RES],16 days,1996,Chemicals and FertilizersTextilesCommerce and ...,NaN,Bharatiya Janata Party,Vajpayee I,Shankar Dayal Sharma (1992–1997)
28,NaN,H. D. Deve Gowda (born 1933) MP for Karnataka ...,"63 years, 14 days",1 June 1996,21 April 1997[RES],324 days,–,Home Affairs (1996)Agriculture (1996)Textiles ...,NaN,Janata Dal (United Front),Deve Gowda,Shankar Dayal Sharma (1992–1997)
29,NaN,Inder Kumar Gujral (1919–2012) MP for Bihar (R...,"77 years, 138 days",21 April 1997,19 March 1998[RES],332 days,–,"Personnel, Public Grievances and PensionsExter...",NaN,Janata Dal (United Front),Gujral,Shankar Dayal Sharma (1992–1997)
30,NaN,Inder Kumar Gujral (1919–2012) MP for Bihar (R...,"77 years, 138 days",21 April 1997,19 March 1998[RES],332 days,–,"Personnel, Public Grievances and PensionsExter...",NaN,Janata Dal (United Front),Gujral,K. R. Narayanan (1997–2002)
31,NaN,Atal Bihari Vajpayee (1924–2018) MP for Lucknow,"73 years, 84 days",19 March 1998[§],22 May 2004[DIS],"6 years, 64 days",1998,External Affairs (1998)Information and Broadca...,NaN,Bharatiya Janata Party (National Democratic Al...,Vajpayee II,K. R. Narayanan (1997–2002)
32,NaN,Atal Bihari Vajpayee (1924–2018) MP for Lucknow,"73 years, 84 days",19 March 1998[§],22 May 2004[DIS],"6 years, 64 days",1999,External Affairs (1998)Information and Broadca...,NaN,Bharatiya Janata Party (National Democratic Al...,Vajpayee III,K. R. Narayanan (1997–2002)
33,NaN,Atal Bihari Vajpayee (1924–2018) MP for Lucknow,"73 years, 84 days",19 March 1998[§],22 May 2004[DIS],"6 years, 64 days",1999,External Affairs (1998)Information and Broadca...,NaN,Bharatiya Janata Party (National Democratic Al...,Vajpayee III,A. P. J. Abdul Kalam (2002–2007)
34,NaN,Manmohan Singh (1932–2024) MP for Assam (Rajya...,"71 years, 239 days",22 May 2004,26 May 2014[DIS],"10 years, 4 days",2004,"Personnel, Public Grievances and PensionsAtomi...",NaN,Indian National Congress (United Progressive A...,Manmohan I,A. P. J. Abdul Kalam (2002–2007)
35,NaN,Manmohan Singh (1932–2024) MP for Assam (Rajya...,"71 years, 239 days",22 May 2004,26 May 2014[DIS],"10 years, 4 days",2004,"Personnel, Public Grievances and PensionsAtomi...",NaN,Indian National Congress (United Progressive A...,Manmohan I,Pratibha Patil (2007–2012)
36,NaN,Manmohan Singh (1932–2024) MP for Assam (Rajya...,"71 years, 239 days",22 May 2004,26 May 2014[DIS],"10 years, 4 days",2009,"Personnel, Public Grievances and PensionsAtomi...",NaN,Indian National Congress (United Progressive A...,Manmohan II,Pratibha Patil (2007–2012)
37,NaN,Manmohan Singh (1932–2024) MP for Assam (Rajya...,"71 years, 239 days",22 May 2004,26 May 2014[DIS],"10 years, 4 days",2009,"Personnel, Public Grievances and PensionsAtomi...",NaN,Indian National Congress (United Progressive A...,Manmohan II,Pranab Mukherjee (2012–2017)
38,NaN,Narendra Modi (born 1950) MP for Varanasi,"63 years, 251 days",26 May 2014,Incumbent,"11 years, 303 days",2014,"Personnel, Public Grievances and PensionsAtomi...",NaN,Bharatiya Janata Party (National Democratic Al...,Modi I,Pranab Mukherjee (2012–2017)
39,NaN,Narendra Modi (born 1950) MP for Varanasi,"63 years, 251 days",26 May 2014,Incumbent,"11 years, 303 days",2014,"Personnel, Public Grievances and PensionsAtomi...",NaN,Bharatiya Janata Party (National Democratic Al...,Modi I,Ram Nath Kovind (2017–2022)
40,NaN,Narendra Modi (born 1950) MP for Varanasi,"63 years, 251 days",26 May 2014,Incumbent,"11 years, 303 days",2019,"Personnel, Public Grievances and PensionsAtomi...",NaN,Bharatiya Janata Party (National Democratic Al...,Modi II,Ram Nath Kovind (2017–2022)
41,NaN,Narendra Modi (born 1950) MP for Varanasi,"63 years, 251 days",26 May 2014,Incumbent,"11 years, 303 days",2019,"Personnel, Public Grievances and PensionsAtomi...",NaN,Bharatiya Janata Party (National Democratic Al...,Modi II,Droupadi Murmu (2022–present)
42,NaN,Narendra Modi (born 1950) MP for Varanasi,"63 years, 251 days",26 May 2014,Incumbent,"11 years, 303 days",2024,"Personnel, Public Grievances and PensionsAtomi...",NaN,Bharatiya Janata Party (National Democratic Al...,Modi III,Droupadi Murmu (2022–present)

In [71]:
html[0].to_html('PMs_of_India.html')         # storing/converting dataframe to html file